# Random Forest Test

In [1]:
import pandas as pd
import numpy as np

## Definindos os metodos para o Pipeline

In [2]:
def build_cube(col, row, week):
    X = np.array([
        df.col.values,
        df.row.values,
        df.week_number.values
    ])

    new_x = [[], [], []]
    for i in range(len(X[0])):
        if 0 < X[2][i] < 261:
            new_x[0].append(X[0][i])
            new_x[1].append(X[1][i])
            new_x[2].append(X[2][i])

    X = new_x
    
    dim = [max(X[2]) + 1, max(X[1]) + 1, max(X[0]) + 1]

    cube = []
    for i in range(dim[0]):
        cube.append([])

        for j in range(dim[1]):
            cube[i].append([])

            for k in range(dim[2]):
                cube[i][j].append(0)
                
    for i in range(len(X[0])):
        cube[X[2][i]][X[1][i]][X[0][i]] += 1
    
    return cube

In [3]:
def split_cube(cube):
    new_x = []
    y = []
    for w in range(len(cube)):
        for r in range(len(cube[0])):
            for c in range(len(cube[0][0])):
                new_x.append(np.array([w,r,c]))
                y.append(cube[w][r][c])
    return np.array(new_x), y

def convert_y_to_binary(y):
    y2 = pd.DataFrame(y, columns=['y']) > 0
    return y2.astype(int).values

# Random Forest

In [4]:
from sklearn.model_selection import train_test_split

# Separando Treino e Teste
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

In [5]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import  RandomForestClassifier
from sklearn import metrics

def predict_with_rf(X_train, X_test, y_train, y_test):
    clf = Pipeline([('sc', StandardScaler()), ('rf', RandomForestClassifier())])
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    
    print('Accuracy:', metrics.accuracy_score(y_test, y_pred))
    return y_pred

## Convertendo os resultados da predição e os dados reais para um cubo [Semana, Coluna e Linha]

In [6]:
def result_to_cube(y_test, y_pred):
    real = [[],[],[]]
    pred = [[],[],[]]
    for i in range(len(y_pred)):
        x = X_test[i]
        if y_test[i][0] > 0:
            for l in range(y_test[i][0]):
                real[0].append(x[0])
                real[1].append(x[1])
                real[2].append(x[2])

        if y_pred[i] > 0:
            for l in range(y_pred[i]):
                pred[0].append(x[0])
                pred[1].append(x[1])
                pred[2].append(x[2])
    cube_r = build_cube(real[0], real[1], real[2])
    cube_p = build_cube(pred[0], pred[1], pred[2])
    return cube_r, cube_p

In [7]:
def compara_acertos(X_test, y_test, y_pred):
    positivo = 0
    acerto = 0
    for i in range(len(y_pred)):
        if y_pred[i] == 1 or y_test[i][0] == 1:
            if  y_pred[i] == y_test[i][0]:
                acerto += 1
            positivo += 1
            
            print(X_test[i], y_pred[i], y_test[i][0],  y_pred[i] == y_test[i][0])
    
    return acerto/positivo

## Pipeline com granularidade 10
Celulas com tamanho de 0.1°

In [8]:
df = pd.read_excel('dataframe_6.xlsx')

In [9]:
X, y = split_cube(build_cube(df.col.values, df.row.values, df.week_number.values))
y = convert_y_to_binary(y)

In [10]:
from sklearn.model_selection import train_test_split

# Separando Treino e Teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

In [10]:
y_pred = predict_with_rf(X_train, X_test, y_train, y_test)
acerto = compara_acertos(X_test, y_test, y_pred)
print("Taxa de acerto: ", acerto)

/home/andre/.local/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/home/andre/.local/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/home/andre/.local/lib/python3.6/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/andre/.local/lib/python3.6/site-packages/sklearn/pipeline.py:267: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self._final_estimator.fit(Xt, y, **fit_params)
/home/andre/.local/lib/python3.6/site-packages/skle

Accuracy: 0.9071979365377898
[208  24  20] 1 1 True
[208  25   7] 0 1 False
[208  25  15] 1 1 True
[208  25  18] 0 1 False
[208  25  20] 1 1 True
[208  26   9] 0 1 False
[208  26  18] 0 1 False
[208  27  18] 0 1 False
[208  28  14] 0 1 False
[209   0   1] 0 1 False
[209   0   4] 1 1 True
[209   0  10] 1 1 True
[209   1   6] 1 1 True
[209   1   7] 1 1 True
[209   1   8] 0 1 False
[209   1   9] 0 1 False
[209   1  10] 1 1 True
[209   1  11] 1 1 True
[209   1  12] 1 1 True
[209   2   1] 1 1 True
[209   2   2] 1 1 True
[209   2   3] 1 0 False
[209   2   4] 1 1 True
[209   2   5] 1 1 True
[209   2   6] 1 1 True
[209   2   7] 0 1 False
[209   2   9] 1 1 True
[209   2  10] 0 1 False
[209   2  11] 0 1 False
[209   2  12] 1 1 True
[209   3   5] 1 1 True
[209   3   6] 1 0 False
[209   3   7] 1 1 True
[209   3  10] 1 1 True
[209   3  12] 1 1 True
[209   3  13] 1 1 True
[209   4   1] 1 1 True
[209   4   4] 1 0 False
[209   4   5] 1 1 True
[209   4   8] 1 0 False
[209   4   9] 1 0 False
[209   4  1

[213   8  10] 1 0 False
[213   8  12] 0 1 False
[213   8  13] 0 1 False
[213   8  14] 1 1 True
[213   8  15] 1 1 True
[213   8  16] 1 1 True
[213   9   6] 1 1 True
[213   9  10] 1 1 True
[213   9  11] 1 0 False
[213   9  12] 0 1 False
[213   9  13] 1 1 True
[213   9  14] 1 0 False
[213   9  15] 1 1 True
[213   9  16] 1 1 True
[213  10  11] 0 1 False
[213  10  12] 1 1 True
[213  10  13] 1 1 True
[213  10  14] 0 1 False
[213  10  15] 0 1 False
[213  10  16] 0 1 False
[213  11   9] 1 1 True
[213  11  13] 1 0 False
[213  11  14] 1 0 False
[213  11  15] 1 1 True
[213  11  17] 1 1 True
[213  12  11] 0 1 False
[213  12  14] 1 1 True
[213  12  15] 0 1 False
[213  12  17] 1 1 True
[213  13  14] 1 0 False
[213  13  15] 1 1 True
[213  13  19] 0 1 False
[213  14   7] 1 1 True
[213  14   9] 1 0 False
[213  14  11] 1 1 True
[213  14  15] 1 1 True
[213  14  16] 1 1 True
[213  15   7] 0 1 False
[213  15  11] 1 1 True
[213  15  12] 0 1 False
[213  15  14] 0 1 False
[213  15  16] 1 0 False
[213  15  17]

[217   2  12] 1 1 True
[217   3   1] 0 1 False
[217   3   5] 1 0 False
[217   3   6] 1 1 True
[217   3   7] 1 0 False
[217   3  10] 1 0 False
[217   3  12] 1 1 True
[217   3  13] 1 1 True
[217   4   1] 1 1 True
[217   4   4] 1 0 False
[217   4   5] 1 1 True
[217   4   7] 0 1 False
[217   4   8] 1 0 False
[217   4   9] 1 0 False
[217   4  13] 1 1 True
[217   4  14] 1 1 True
[217   5   8] 1 0 False
[217   5   9] 1 0 False
[217   5  10] 1 1 True
[217   5  11] 1 1 True
[217   5  14] 1 1 True
[217   6   1] 0 1 False
[217   6   2] 1 1 True
[217   6   6] 1 1 True
[217   6   7] 0 1 False
[217   6  11] 1 1 True
[217   6  13] 1 1 True
[217   6  14] 1 1 True
[217   6  15] 1 1 True
[217   7   2] 1 1 True
[217   7   7] 0 1 False
[217   7  13] 1 1 True
[217   7  14] 1 1 True
[217   7  15] 1 1 True
[217   7  16] 1 0 False
[217   8   5] 0 1 False
[217   8   9] 0 1 False
[217   8  10] 1 1 True
[217   8  14] 1 1 True
[217   8  15] 1 1 True
[217   8  16] 1 1 True
[217   9   6] 1 1 True
[217   9  10] 1 1 

[220  24   8] 1 0 False
[220  24  11] 0 1 False
[220  24  14] 0 1 False
[220  24  15] 1 1 True
[220  24  16] 1 1 True
[220  24  20] 1 1 True
[220  25  15] 1 1 True
[220  25  18] 0 1 False
[220  25  20] 1 1 True
[220  26   9] 0 1 False
[220  26  18] 0 1 False
[220  27  10] 0 1 False
[220  27  18] 0 1 False
[220  28   9] 0 1 False
[220  28  14] 0 1 False
[221   0   4] 1 1 True
[221   0  10] 1 1 True
[221   1   6] 1 1 True
[221   1   7] 1 1 True
[221   1   8] 0 1 False
[221   1   9] 0 1 False
[221   1  10] 1 1 True
[221   1  11] 1 1 True
[221   1  12] 1 1 True
[221   2   1] 1 1 True
[221   2   2] 1 1 True
[221   2   3] 1 1 True
[221   2   4] 1 1 True
[221   2   5] 1 0 False
[221   2   6] 1 0 False
[221   2   9] 1 1 True
[221   2  11] 0 1 False
[221   2  12] 1 1 True
[221   3   1] 0 1 False
[221   3   5] 1 1 True
[221   3   6] 1 1 True
[221   3   7] 1 1 True
[221   3  10] 1 1 True
[221   3  11] 0 1 False
[221   3  12] 1 1 True
[221   3  13] 1 1 True
[221   4   1] 1 0 False
[221   4   4] 1 

[224   7  16] 1 1 True
[224   8   9] 0 1 False
[224   8  10] 1 0 False
[224   8  14] 1 1 True
[224   8  15] 1 1 True
[224   8  16] 1 1 True
[224   9   6] 1 1 True
[224   9   7] 0 1 False
[224   9  10] 1 1 True
[224   9  11] 1 1 True
[224   9  12] 0 1 False
[224   9  13] 1 0 False
[224   9  14] 1 0 False
[224   9  15] 1 1 True
[224   9  16] 1 1 True
[224  10   7] 0 1 False
[224  10  11] 0 1 False
[224  10  12] 1 1 True
[224  10  13] 1 1 True
[224  10  16] 0 1 False
[224  11   9] 1 0 False
[224  11  13] 1 0 False
[224  11  14] 1 1 True
[224  11  15] 1 1 True
[224  11  17] 1 1 True
[224  12  10] 0 1 False
[224  12  11] 0 1 False
[224  12  14] 1 1 True
[224  12  17] 1 0 False
[224  13  14] 1 1 True
[224  13  15] 1 1 True
[224  14   7] 1 1 True
[224  14   9] 1 0 False
[224  14  10] 0 1 False
[224  14  11] 1 1 True
[224  14  12] 0 1 False
[224  14  15] 1 0 False
[224  14  16] 1 1 True
[224  15  11] 1 1 True
[224  15  16] 1 1 True
[224  15  17] 1 1 True
[224  16  12] 1 0 False
[224  16  17] 1

[228   5  10] 1 1 True
[228   5  11] 1 1 True
[228   5  13] 0 1 False
[228   5  14] 1 1 True
[228   6   2] 1 1 True
[228   6   4] 0 1 False
[228   6   5] 0 1 False
[228   6   6] 1 1 True
[228   6  10] 0 1 False
[228   6  11] 1 1 True
[228   6  12] 0 1 False
[228   6  13] 1 1 True
[228   6  14] 1 1 True
[228   6  15] 1 1 True
[228   7   2] 1 1 True
[228   7  13] 1 1 True
[228   7  14] 1 1 True
[228   7  15] 1 1 True
[228   7  16] 1 0 False
[228   8  10] 1 0 False
[228   8  14] 1 1 True
[228   8  15] 1 1 True
[228   8  16] 1 1 True
[228   9   5] 0 1 False
[228   9   6] 1 1 True
[228   9  10] 1 1 True
[228   9  11] 1 0 False
[228   9  12] 0 1 False
[228   9  13] 1 0 False
[228   9  14] 1 1 True
[228   9  15] 1 1 True
[228   9  16] 1 1 True
[228  10  11] 0 1 False
[228  10  12] 1 1 True
[228  10  13] 1 1 True
[228  10  16] 0 1 False
[228  11   9] 1 1 True
[228  11  13] 1 1 True
[228  11  14] 1 0 False
[228  11  15] 1 1 True
[228  11  17] 1 1 True
[228  12  10] 0 1 False
[228  12  11] 0 1 F

[232   4   9] 1 0 False
[232   4  13] 1 1 True
[232   4  14] 1 1 True
[232   5   3] 0 1 False
[232   5   6] 0 1 False
[232   5   8] 1 0 False
[232   5   9] 1 0 False
[232   5  10] 1 0 False
[232   5  11] 1 1 True
[232   5  14] 1 1 True
[232   6   2] 1 1 True
[232   6   6] 1 1 True
[232   6  11] 1 1 True
[232   6  13] 1 1 True
[232   6  14] 1 1 True
[232   6  15] 1 1 True
[232   7   2] 1 1 True
[232   7   3] 0 1 False
[232   7  13] 1 1 True
[232   7  14] 1 1 True
[232   7  15] 1 1 True
[232   7  16] 1 0 False
[232   8   5] 0 1 False
[232   8   7] 0 1 False
[232   8   9] 0 1 False
[232   8  10] 1 0 False
[232   8  13] 0 1 False
[232   8  14] 1 1 True
[232   8  15] 1 1 True
[232   8  16] 1 1 True
[232   9   6] 1 1 True
[232   9  10] 1 1 True
[232   9  11] 1 0 False
[232   9  12] 0 1 False
[232   9  13] 1 0 False
[232   9  14] 1 0 False
[232   9  15] 1 1 True
[232   9  16] 1 1 True
[232  10   6] 0 1 False
[232  10  11] 0 1 False
[232  10  12] 1 1 True
[232  10  13] 1 1 True
[232  10  16] 0

[235  15  17] 1 1 True
[235  16  12] 1 0 False
[235  16  17] 1 1 True
[235  17   9] 0 1 False
[235  17  14] 1 1 True
[235  17  17] 1 0 False
[235  18  11] 1 1 True
[235  18  16] 1 1 True
[235  18  17] 1 1 True
[235  19   7] 0 1 False
[235  19  12] 1 1 True
[235  19  19] 0 1 False
[235  20   8] 0 1 False
[235  20  10] 1 0 False
[235  20  12] 0 1 False
[235  20  14] 0 1 False
[235  20  17] 1 1 True
[235  20  20] 1 0 False
[235  21   6] 1 0 False
[235  21   7] 1 1 True
[235  21  13] 1 0 False
[235  21  14] 0 1 False
[235  22   3] 0 1 False
[235  22   8] 1 0 False
[235  22   9] 1 1 True
[235  22  13] 1 1 True
[235  22  14] 1 1 True
[235  22  15] 1 1 True
[235  22  19] 1 1 True
[235  22  20] 1 1 True
[235  23   8] 1 0 False
[235  23  13] 1 1 True
[235  23  14] 1 1 True
[235  23  19] 1 0 False
[235  24   8] 1 1 True
[235  24  15] 1 1 True
[235  24  16] 1 0 False
[235  24  20] 1 1 True
[235  25  15] 1 1 True
[235  25  18] 0 1 False
[235  25  20] 1 0 False
[235  26   9] 0 1 False
[235  26  18]

[239   7   2] 1 0 False
[239   7   3] 0 1 False
[239   7  13] 1 1 True
[239   7  14] 1 1 True
[239   7  15] 1 1 True
[239   7  16] 1 0 False
[239   8   5] 0 1 False
[239   8   9] 0 1 False
[239   8  10] 1 1 True
[239   8  14] 1 1 True
[239   8  15] 1 1 True
[239   8  16] 1 1 True
[239   9   6] 1 1 True
[239   9  10] 1 1 True
[239   9  11] 1 1 True
[239   9  12] 0 1 False
[239   9  13] 1 1 True
[239   9  14] 1 0 False
[239   9  15] 1 1 True
[239   9  16] 1 1 True
[239  10  12] 1 1 True
[239  10  13] 1 1 True
[239  10  16] 0 1 False
[239  11   9] 1 0 False
[239  11  13] 1 0 False
[239  11  14] 1 1 True
[239  11  15] 1 1 True
[239  11  16] 0 1 False
[239  11  17] 1 1 True
[239  12  11] 0 1 False
[239  12  14] 1 1 True
[239  12  15] 0 1 False
[239  12  17] 1 0 False
[239  13  14] 1 0 False
[239  13  15] 1 1 True
[239  14   7] 1 1 True
[239  14   9] 1 0 False
[239  14  10] 0 1 False
[239  14  11] 1 1 True
[239  14  15] 1 1 True
[239  14  16] 1 1 True
[239  15  11] 1 0 False
[239  15  12] 0 

[243   4   3] 0 1 False
[243   4   4] 1 0 False
[243   4   5] 1 1 True
[243   4   8] 1 0 False
[243   4   9] 1 0 False
[243   4  13] 1 1 True
[243   4  14] 1 1 True
[243   5   3] 0 1 False
[243   5   8] 1 0 False
[243   5   9] 1 0 False
[243   5  10] 1 0 False
[243   5  11] 1 1 True
[243   5  13] 0 1 False
[243   5  14] 1 1 True
[243   6   2] 1 1 True
[243   6   5] 0 1 False
[243   6   6] 1 1 True
[243   6   7] 0 1 False
[243   6   9] 0 1 False
[243   6  11] 1 1 True
[243   6  12] 0 1 False
[243   6  13] 1 1 True
[243   6  14] 1 1 True
[243   6  15] 1 1 True
[243   7   1] 0 1 False
[243   7   2] 1 1 True
[243   7  13] 1 1 True
[243   7  14] 1 1 True
[243   7  15] 1 1 True
[243   7  16] 1 1 True
[243   8   7] 0 1 False
[243   8   9] 0 1 False
[243   8  10] 1 1 True
[243   8  13] 0 1 False
[243   8  14] 1 1 True
[243   8  15] 1 1 True
[243   8  16] 1 1 True
[243   9   6] 1 1 True
[243   9  10] 1 1 True
[243   9  11] 1 0 False
[243   9  12] 0 1 False
[243   9  13] 1 1 True
[243   9  14] 1

[246  21   7] 1 1 True
[246  21  13] 1 0 False
[246  21  14] 0 1 False
[246  22   6] 0 1 False
[246  22   8] 1 0 False
[246  22   9] 1 1 True
[246  22  13] 1 1 True
[246  22  14] 1 1 True
[246  22  15] 1 1 True
[246  22  19] 1 1 True
[246  22  20] 1 1 True
[246  23   8] 1 0 False
[246  23  11] 0 1 False
[246  23  12] 0 1 False
[246  23  13] 1 1 True
[246  23  14] 1 1 True
[246  23  19] 1 1 True
[246  24   8] 1 0 False
[246  24  14] 0 1 False
[246  24  15] 1 1 True
[246  24  16] 1 1 True
[246  24  20] 1 1 True
[246  25  15] 1 1 True
[246  25  18] 0 1 False
[246  25  20] 1 0 False
[246  26   9] 0 1 False
[246  26  18] 0 1 False
[246  27  18] 0 1 False
[246  28  12] 0 1 False
[246  28  14] 0 1 False
[246  28  15] 0 1 False
[246  29  12] 0 1 False
[247   0   4] 1 1 True
[247   0   6] 0 1 False
[247   0   7] 0 1 False
[247   0   8] 0 1 False
[247   0   9] 0 1 False
[247   0  10] 1 0 False
[247   1   6] 1 1 True
[247   1   7] 1 1 True
[247   1   8] 0 1 False
[247   1   9] 0 1 False
[247   1 

[250  11  13] 1 0 False
[250  11  14] 1 1 True
[250  11  15] 1 1 True
[250  11  17] 1 1 True
[250  12  11] 0 1 False
[250  12  14] 1 1 True
[250  12  15] 0 1 False
[250  12  17] 1 0 False
[250  13  14] 1 1 True
[250  13  15] 1 1 True
[250  14   7] 1 1 True
[250  14   9] 1 0 False
[250  14  10] 0 1 False
[250  14  11] 1 1 True
[250  14  15] 1 1 True
[250  14  16] 1 1 True
[250  15  11] 1 1 True
[250  15  12] 0 1 False
[250  15  16] 1 0 False
[250  15  17] 1 1 True
[250  16  12] 1 0 False
[250  16  17] 1 1 True
[250  17  10] 0 1 False
[250  17  12] 0 1 False
[250  17  13] 0 1 False
[250  17  14] 1 1 True
[250  17  17] 1 0 False
[250  18  11] 1 1 True
[250  18  16] 1 1 True
[250  18  17] 1 1 True
[250  19  12] 1 1 True
[250  20  10] 1 1 True
[250  20  14] 0 1 False
[250  20  17] 1 1 True
[250  20  20] 1 1 True
[250  21   6] 1 1 True
[250  21   7] 1 1 True
[250  21  10] 0 1 False
[250  21  13] 1 0 False
[250  22   8] 1 0 False
[250  22   9] 1 1 True
[250  22  13] 1 1 True
[250  22  14] 1 1

[254   2   3] 1 0 False
[254   2   4] 1 1 True
[254   2   5] 1 1 True
[254   2   6] 1 1 True
[254   2   9] 1 1 True
[254   2  12] 1 1 True
[254   3   5] 1 1 True
[254   3   6] 1 1 True
[254   3   7] 1 1 True
[254   3  10] 1 1 True
[254   3  12] 1 1 True
[254   3  13] 1 1 True
[254   4   1] 1 0 False
[254   4   4] 1 0 False
[254   4   5] 1 1 True
[254   4   8] 1 0 False
[254   4   9] 1 0 False
[254   4  12] 0 1 False
[254   4  13] 1 1 True
[254   4  14] 1 1 True
[254   5   3] 0 1 False
[254   5   8] 1 0 False
[254   5   9] 1 0 False
[254   5  10] 1 0 False
[254   5  11] 1 1 True
[254   5  13] 0 1 False
[254   5  14] 1 1 True
[254   6   2] 1 1 True
[254   6   4] 0 1 False
[254   6   6] 1 1 True
[254   6   7] 0 1 False
[254   6   9] 0 1 False
[254   6  11] 1 1 True
[254   6  13] 1 1 True
[254   6  14] 1 1 True
[254   6  15] 1 1 True
[254   7   2] 1 1 True
[254   7  13] 1 1 True
[254   7  14] 1 1 True
[254   7  15] 1 1 True
[254   7  16] 1 0 False
[254   8   5] 0 1 False
[254   8  10] 1 0 

[257  22  13] 1 1 True
[257  22  14] 1 1 True
[257  22  15] 1 1 True
[257  22  19] 1 1 True
[257  22  20] 1 1 True
[257  23   8] 1 0 False
[257  23  13] 1 1 True
[257  23  14] 1 1 True
[257  23  19] 1 1 True
[257  24   8] 1 0 False
[257  24  15] 1 1 True
[257  24  16] 1 0 False
[257  24  20] 1 1 True
[257  25  15] 1 1 True
[257  25  18] 0 1 False
[257  25  20] 1 1 True
[257  26   9] 0 1 False
[257  26  18] 0 1 False
[257  28  12] 0 1 False
[257  28  14] 0 1 False
[257  28  15] 0 1 False
[257  29  12] 0 1 False
[257  29  22] 0 1 False
[257  30  12] 0 1 False
[258   0   4] 1 1 True
[258   0  10] 1 1 True
[258   1   6] 1 1 True
[258   1   7] 1 1 True
[258   1   8] 0 1 False
[258   1   9] 0 1 False
[258   1  10] 1 1 True
[258   1  11] 1 1 True
[258   1  12] 1 1 True
[258   2   1] 1 1 True
[258   2   2] 1 1 True
[258   2   3] 1 0 False
[258   2   4] 1 1 True
[258   2   5] 1 1 True
[258   2   6] 1 1 True
[258   2   9] 1 1 True
[258   2  12] 1 1 True
[258   3   0] 0 1 False
[258   3   5] 1 1 

## Pipeline com granularidade 100
Celulas com tamanho de 0.01°

In [11]:
df = pd.read_excel('dataframe_7.xlsx')

In [12]:
X, y = split_cube(build_cube(df.col.values, df.row.values, df.week_number.values))
y = convert_y_to_binary(y)

In [13]:
from sklearn.model_selection import train_test_split

# Separando Treino e Teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

In [13]:

y_pred = predict_with_rf(X_train, X_test, y_train, y_test)
acerto = compara_acertos(X_test, y_test, y_pred)
print("Taxa de acerto: ", acerto)

/home/andre/.local/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/home/andre/.local/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/home/andre/.local/lib/python3.6/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/andre/.local/lib/python3.6/site-packages/sklearn/pipeline.py:267: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self._final_estimator.fit(Xt, y, **fit_params)
/home/andre/.local/lib/python3.6/site-packages/skle

Accuracy: 0.995159941568534
[208 245 150] 0 1 False
[208 246 150] 0 1 False
[208 250 187] 1 0 False
[208 252  78] 0 1 False
[208 254 185] 0 1 False
[208 256 187] 0 1 False
[208 258 158] 0 1 False
[208 258 209] 0 1 False
[208 262  96] 0 1 False
[208 262  97] 1 1 True
[208 263  96] 1 0 False
[208 269 184] 1 1 True
[208 270 184] 1 1 True
[208 271 184] 0 1 False
[208 286 143] 0 1 False
[208 287 143] 0 1 False
[208 290 127] 1 0 False
[209   4  46] 0 1 False
[209   5  18] 0 1 False
[209   5  45] 1 0 False
[209   6  48] 1 0 False
[209   9 101] 1 1 True
[209  10 101] 0 1 False
[209  10 102] 1 1 True
[209  10 103] 1 0 False
[209  11  69] 1 0 False
[209  11 102] 1 0 False
[209  11 103] 1 1 True
[209  12 103] 0 1 False
[209  13  67] 0 1 False
[209  13  68] 1 0 False
[209  13  69] 0 1 False
[209  13  86] 0 1 False
[209  14  64] 0 1 False
[209  14  65] 1 0 False
[209  14  66] 0 1 False
[209  14  67] 0 1 False
[209  14  68] 1 1 True
[209  14  69] 1 1 True
[209  14  70] 1 1 True
[209  14 104] 1 0 Fal

[209 177  95] 0 1 False
[209 180 169] 0 1 False
[209 180 170] 1 1 True
[209 180 209] 1 0 False
[209 181 169] 0 1 False
[209 183 161] 1 0 False
[209 184 172] 0 1 False
[209 185 117] 1 1 True
[209 194  78] 0 1 False
[209 196 125] 1 0 False
[209 197 126] 1 0 False
[209 198 126] 1 1 True
[209 200 140] 1 0 False
[209 200 141] 0 1 False
[209 200 179] 0 1 False
[209 205 203] 1 0 False
[209 207 172] 0 1 False
[209 208 121] 0 1 False
[209 208 172] 1 0 False
[209 209 172] 1 1 True
[209 211  78] 1 0 False
[209 211 184] 0 1 False
[209 213  67] 1 1 True
[209 214 131] 1 0 False
[209 222  89] 0 1 False
[209 222 204] 1 1 True
[209 223  90] 0 1 False
[209 223  91] 0 1 False
[209 224  89] 1 0 False
[209 224  90] 1 1 True
[209 224  91] 0 1 False
[209 224 204] 1 1 True
[209 224 205] 1 1 True
[209 225 194] 0 1 False
[209 225 203] 1 1 True
[209 225 204] 1 1 True
[209 225 205] 0 1 False
[209 226  90] 0 1 False
[209 226 157] 1 0 False
[209 226 158] 0 1 False
[209 226 203] 1 0 False
[209 226 204] 1 1 True
[209

[210  84 155] 1 1 True
[210  84 156] 1 0 False
[210  84 160] 1 1 True
[210  84 161] 1 1 True
[210  85  50] 0 1 False
[210  85 150] 1 1 True
[210  85 151] 0 1 False
[210  85 152] 1 1 True
[210  85 153] 1 1 True
[210  85 154] 1 1 True
[210  85 155] 1 1 True
[210  85 156] 1 0 False
[210  85 161] 1 1 True
[210  86 148] 0 1 False
[210  86 149] 1 1 True
[210  86 150] 1 1 True
[210  86 151] 1 0 False
[210  86 154] 1 1 True
[210  86 155] 0 1 False
[210  86 156] 1 0 False
[210  86 157] 0 1 False
[210  86 159] 1 0 False
[210  86 160] 1 1 True
[210  86 161] 1 1 True
[210  87 148] 1 0 False
[210  87 149] 1 1 True
[210  87 150] 1 1 True
[210  87 159] 1 1 True
[210  87 160] 1 1 True
[210  87 161] 1 1 True
[210  88 130] 0 1 False
[210  88 147] 1 0 False
[210  88 148] 1 0 False
[210  88 150] 1 0 False
[210  88 161] 0 1 False
[210  88 162] 1 1 True
[210  89 161] 1 0 False
[210  90 127] 0 1 False
[210  91  67] 0 1 False
[210  91 119] 1 0 False
[210  92  67] 1 0 False
[210  93 160] 0 1 False
[210  94 158

[211  67 143] 1 1 True
[211  67 144] 1 1 True
[211  67 145] 1 1 True
[211  67 146] 1 1 True
[211  67 147] 1 1 True
[211  67 149] 1 1 True
[211  67 150] 0 1 False
[211  67 151] 0 1 False
[211  67 152] 1 1 True
[211  68  99] 0 1 False
[211  68 136] 0 1 False
[211  68 140] 0 1 False
[211  68 141] 1 1 True
[211  68 142] 1 0 False
[211  68 143] 0 1 False
[211  68 144] 1 1 True
[211  68 145] 1 1 True
[211  68 146] 1 1 True
[211  68 147] 1 1 True
[211  68 148] 1 1 True
[211  68 149] 1 1 True
[211  68 150] 1 1 True
[211  68 151] 0 1 False
[211  68 152] 1 0 False
[211  69 140] 1 1 True
[211  69 141] 1 1 True
[211  69 142] 0 1 False
[211  69 143] 1 1 True
[211  69 144] 1 1 True
[211  69 147] 1 1 True
[211  69 148] 1 1 True
[211  69 149] 1 1 True
[211  69 150] 1 1 True
[211  69 151] 1 1 True
[211  70 139] 1 1 True
[211  70 140] 1 0 False
[211  70 141] 0 1 False
[211  70 143] 0 1 False
[211  70 145] 0 1 False
[211  70 147] 1 1 True
[211  70 148] 1 1 True
[211  70 149] 1 1 True
[211  70 150] 1 1 Tr

[212  20  39] 1 0 False
[212  20  98] 1 1 True
[212  20 121] 0 1 False
[212  21  41] 0 1 False
[212  21  42] 0 1 False
[212  21  68] 1 0 False
[212  21  97] 1 0 False
[212  21  98] 1 0 False
[212  22  11] 0 1 False
[212  22  12] 1 1 True
[212  22  13] 1 1 True
[212  23  12] 1 1 True
[212  23  13] 1 1 True
[212  23  20] 1 0 False
[212  23  26] 0 1 False
[212  23  53] 1 0 False
[212  23 122] 1 1 True
[212  25 124] 1 0 False
[212  26 124] 1 1 True
[212  26 125] 1 0 False
[212  26 126] 1 1 True
[212  27  66] 1 1 True
[212  27 105] 0 1 False
[212  27 126] 1 1 True
[212  27 127] 1 1 True
[212  29 103] 0 1 False
[212  31 128] 1 1 True
[212  32  61] 1 0 False
[212  32  79] 1 1 True
[212  32 127] 0 1 False
[212  32 129] 1 1 True
[212  32 130] 1 1 True
[212  33 128] 0 1 False
[212  33 129] 1 1 True
[212  33 130] 1 1 True
[212  34 129] 0 1 False
[212  34 130] 1 1 True
[212  34 131] 1 1 True
[212  35 127] 1 0 False
[212  35 128] 1 1 True
[212  35 130] 1 1 True
[212  35 131] 1 1 True
[212  35 132] 

[212 194  78] 0 1 False
[212 196 125] 1 0 False
[212 197 126] 1 0 False
[212 198 126] 1 1 True
[212 200 140] 1 0 False
[212 205 203] 1 0 False
[212 207 167] 0 1 False
[212 208 172] 1 1 True
[212 209 172] 1 1 True
[212 210  71] 0 1 False
[212 211  78] 1 0 False
[212 213  67] 1 1 True
[212 214 131] 1 0 False
[212 222 204] 1 1 True
[212 224  89] 1 0 False
[212 224  90] 1 1 True
[212 224 204] 1 1 True
[212 224 205] 1 1 True
[212 225 194] 0 1 False
[212 225 203] 1 1 True
[212 225 204] 1 1 True
[212 225 205] 0 1 False
[212 226 157] 1 1 True
[212 226 195] 0 1 False
[212 226 203] 1 1 True
[212 226 204] 1 1 True
[212 226 205] 1 1 True
[212 227 190] 0 1 False
[212 227 193] 0 1 False
[212 227 194] 1 1 True
[212 227 195] 1 1 True
[212 227 196] 0 1 False
[212 227 202] 0 1 False
[212 228 139] 0 1 False
[212 228 140] 1 0 False
[212 228 141] 0 1 False
[212 228 190] 1 1 True
[212 228 191] 0 1 False
[212 228 192] 1 1 True
[212 228 193] 1 1 True
[212 228 194] 1 1 True
[212 228 195] 1 1 True
[212 229 139]

[213  84 152] 1 1 True
[213  84 153] 1 1 True
[213  84 154] 1 1 True
[213  84 155] 1 1 True
[213  84 156] 1 0 False
[213  84 160] 1 1 True
[213  84 161] 1 1 True
[213  85 150] 1 1 True
[213  85 151] 0 1 False
[213  85 152] 1 1 True
[213  85 153] 1 1 True
[213  85 154] 1 1 True
[213  85 155] 1 1 True
[213  85 156] 1 0 False
[213  85 160] 0 1 False
[213  85 161] 1 1 True
[213  86 149] 1 1 True
[213  86 150] 1 1 True
[213  86 151] 1 1 True
[213  86 154] 1 1 True
[213  86 155] 0 1 False
[213  86 156] 1 1 True
[213  86 157] 0 1 False
[213  86 159] 1 1 True
[213  86 160] 1 0 False
[213  86 161] 1 1 True
[213  87 148] 1 1 True
[213  87 149] 1 1 True
[213  87 150] 1 0 False
[213  87 159] 1 0 False
[213  87 160] 1 1 True
[213  87 161] 1 1 True
[213  87 162] 0 1 False
[213  88 147] 1 0 False
[213  88 148] 1 1 True
[213  88 150] 1 1 True
[213  88 151] 0 1 False
[213  88 152] 0 1 False
[213  88 161] 0 1 False
[213  88 162] 1 1 True
[213  89 127] 0 1 False
[213  89 145] 0 1 False
[213  89 161] 1 1 

[214  66 141] 1 1 True
[214  66 142] 1 1 True
[214  66 143] 1 1 True
[214  66 144] 1 1 True
[214  66 145] 1 0 False
[214  66 146] 1 1 True
[214  66 147] 1 1 True
[214  66 148] 1 1 True
[214  66 149] 1 1 True
[214  66 150] 1 1 True
[214  66 151] 1 1 True
[214  66 152] 1 1 True
[214  67  66] 0 1 False
[214  67  67] 0 1 False
[214  67 137] 0 1 False
[214  67 138] 1 0 False
[214  67 139] 0 1 False
[214  67 140] 1 1 True
[214  67 141] 1 1 True
[214  67 142] 1 1 True
[214  67 143] 1 1 True
[214  67 144] 1 1 True
[214  67 145] 1 1 True
[214  67 146] 1 1 True
[214  67 147] 1 1 True
[214  67 149] 1 1 True
[214  67 152] 1 1 True
[214  68  99] 0 1 False
[214  68 140] 0 1 False
[214  68 141] 1 1 True
[214  68 142] 1 0 False
[214  68 143] 0 1 False
[214  68 144] 1 1 True
[214  68 145] 1 1 True
[214  68 146] 1 1 True
[214  68 147] 1 1 True
[214  68 148] 1 1 True
[214  68 149] 1 1 True
[214  68 150] 1 1 True
[214  68 152] 1 0 False
[214  69 140] 1 1 True
[214  69 141] 1 1 True
[214  69 142] 0 1 False

[215  14  65] 1 1 True
[215  14  68] 1 1 True
[215  14  69] 1 0 False
[215  14  70] 1 1 True
[215  14 104] 1 1 True
[215  15  63] 0 1 False
[215  15  64] 1 1 True
[215  15  65] 0 1 False
[215  15  66] 1 1 True
[215  15  67] 1 1 True
[215  15  68] 1 1 True
[215  15  69] 1 1 True
[215  15 105] 1 1 True
[215  15 106] 1 1 True
[215  15 107] 1 0 False
[215  15 117] 1 0 False
[215  16  61] 1 1 True
[215  16  62] 0 1 False
[215  16  63] 0 1 False
[215  16  64] 1 1 True
[215  16  65] 1 1 True
[215  16  66] 1 1 True
[215  16  67] 1 0 False
[215  16  68] 1 1 True
[215  16 107] 0 1 False
[215  16 110] 1 1 True
[215  16 117] 1 1 True
[215  17  64] 1 0 False
[215  17  65] 0 1 False
[215  17  66] 1 1 True
[215  17  68] 1 1 True
[215  17 108] 0 1 False
[215  18 116] 1 1 True
[215  18 117] 0 1 False
[215  19 114] 1 1 True
[215  19 115] 1 1 True
[215  19 116] 0 1 False
[215  19 120] 0 1 False
[215  19 121] 1 1 True
[215  20   4] 0 1 False
[215  20  39] 1 0 False
[215  20  41] 0 1 False
[215  20  98] 1 

[215 158 118] 1 0 False
[215 159 173] 1 1 True
[215 159 174] 1 1 True
[215 160 172] 1 1 True
[215 160 173] 1 1 True
[215 160 174] 1 1 True
[215 160 175] 1 1 True
[215 160 176] 1 0 False
[215 161 172] 0 1 False
[215 161 173] 1 1 True
[215 161 174] 1 1 True
[215 162 173] 1 1 True
[215 162 174] 1 1 True
[215 163 173] 0 1 False
[215 163 175] 1 1 True
[215 164 173] 1 0 False
[215 164 174] 1 1 True
[215 164 175] 1 0 False
[215 165 174] 1 0 False
[215 166 173] 1 0 False
[215 167 172] 1 0 False
[215 167 173] 0 1 False
[215 169 121] 1 0 False
[215 173 145] 1 0 False
[215 177  94] 0 1 False
[215 177  95] 0 1 False
[215 177 120] 0 1 False
[215 180 169] 0 1 False
[215 180 170] 1 1 True
[215 180 209] 1 0 False
[215 181 169] 0 1 False
[215 183 161] 1 0 False
[215 185 117] 1 0 False
[215 193  78] 0 1 False
[215 194  77] 0 1 False
[215 196 125] 1 0 False
[215 196 127] 0 1 False
[215 197 126] 1 1 True
[215 198 126] 1 0 False
[215 199 126] 0 1 False
[215 199 141] 0 1 False
[215 200 140] 1 1 True
[215 20

[216  75 153] 1 1 True
[216  76  28] 0 1 False
[216  76  29] 1 1 True
[216  76 143] 0 1 False
[216  76 152] 1 1 True
[216  76 153] 1 1 True
[216  76 158] 0 1 False
[216  77  29] 0 1 False
[216  77 151] 1 1 True
[216  77 152] 1 1 True
[216  77 153] 1 1 True
[216  77 154] 1 1 True
[216  77 155] 1 0 False
[216  77 158] 0 1 False
[216  77 159] 1 0 False
[216  78 152] 1 1 True
[216  78 153] 1 1 True
[216  78 154] 1 1 True
[216  78 155] 1 1 True
[216  78 156] 1 0 False
[216  78 157] 0 1 False
[216  78 158] 0 1 False
[216  78 159] 1 1 True
[216  78 160] 1 1 True
[216  79 149] 1 0 False
[216  79 152] 1 1 True
[216  79 153] 1 1 True
[216  79 154] 1 1 True
[216  79 155] 1 1 True
[216  79 158] 0 1 False
[216  80 103] 1 0 False
[216  80 152] 1 1 True
[216  80 153] 1 1 True
[216  80 154] 1 1 True
[216  80 155] 0 1 False
[216  80 156] 1 0 False
[216  80 159] 1 0 False
[216  80 160] 1 1 True
[216  81  60] 0 1 False
[216  81 128] 0 1 False
[216  81 152] 0 1 False
[216  81 153] 1 1 True
[216  81 154] 1

[217  63 143] 1 1 True
[217  63 144] 1 1 True
[217  63 147] 1 1 True
[217  63 148] 1 1 True
[217  63 149] 1 1 True
[217  63 150] 1 1 True
[217  64  27] 0 1 False
[217  64 134] 1 1 True
[217  64 136] 1 0 False
[217  64 137] 1 0 False
[217  64 138] 1 1 True
[217  64 139] 1 1 True
[217  64 140] 1 1 True
[217  64 141] 1 1 True
[217  64 142] 1 1 True
[217  64 143] 1 1 True
[217  64 144] 1 1 True
[217  64 145] 1 1 True
[217  64 147] 1 1 True
[217  64 148] 1 1 True
[217  64 149] 1 1 True
[217  64 150] 1 1 True
[217  64 151] 1 1 True
[217  65  26] 1 1 True
[217  65 132] 0 1 False
[217  65 137] 1 1 True
[217  65 139] 1 1 True
[217  65 140] 1 1 True
[217  65 141] 1 1 True
[217  65 142] 1 1 True
[217  65 143] 0 1 False
[217  65 144] 1 1 True
[217  65 145] 1 1 True
[217  65 146] 1 1 True
[217  65 147] 1 1 True
[217  65 148] 1 1 True
[217  65 149] 1 1 True
[217  65 150] 1 1 True
[217  65 151] 1 1 True
[217  66  26] 0 1 False
[217  66  67] 1 0 False
[217  66 137] 1 0 False
[217  66 138] 1 1 True
[21

[217 269 184] 1 1 True
[217 270 184] 1 0 False
[217 286 143] 0 1 False
[217 287 142] 0 1 False
[217 287 143] 0 1 False
[217 290 127] 1 0 False
[217 290 128] 0 1 False
[218   4  45] 0 1 False
[218   5  45] 1 0 False
[218   6  48] 1 0 False
[218   6  91] 0 1 False
[218   8  60] 0 1 False
[218   9 101] 1 0 False
[218   9 102] 0 1 False
[218  10 102] 1 1 True
[218  10 103] 1 0 False
[218  11  69] 1 0 False
[218  11 102] 1 0 False
[218  11 103] 1 1 True
[218  13  68] 1 0 False
[218  13  69] 0 1 False
[218  13  85] 0 1 False
[218  13  86] 0 1 False
[218  14  65] 1 1 True
[218  14  66] 0 1 False
[218  14  67] 0 1 False
[218  14  68] 1 1 True
[218  14  69] 1 1 True
[218  14  70] 1 1 True
[218  14 104] 1 0 False
[218  15  64] 1 1 True
[218  15  65] 0 1 False
[218  15  66] 1 1 True
[218  15  67] 1 1 True
[218  15  68] 1 1 True
[218  15  69] 1 1 True
[218  15  70] 0 1 False
[218  15 105] 1 1 True
[218  15 106] 1 1 True
[218  15 107] 1 1 True
[218  15 117] 1 0 False
[218  16  61] 1 1 True
[218  16

[218 133 153] 1 0 False
[218 135 197] 0 1 False
[218 141 160] 1 1 True
[218 142 129] 0 1 False
[218 145 115] 1 1 True
[218 145 117] 1 1 True
[218 146  98] 1 0 False
[218 146 116] 0 1 False
[218 146 117] 1 1 True
[218 147  78] 0 1 False
[218 147 109] 0 1 False
[218 147 113] 1 1 True
[218 147 114] 0 1 False
[218 147 115] 1 1 True
[218 147 116] 0 1 False
[218 147 117] 1 0 False
[218 147 118] 1 1 True
[218 147 165] 1 0 False
[218 148  78] 1 1 True
[218 148  79] 0 1 False
[218 148 114] 1 0 False
[218 148 115] 1 1 True
[218 148 116] 1 0 False
[218 148 118] 0 1 False
[218 148 151] 1 0 False
[218 149  76] 1 1 True
[218 149 102] 0 1 False
[218 149 118] 1 0 False
[218 150 114] 0 1 False
[218 152 168] 1 1 True
[218 158 118] 1 0 False
[218 158 125] 0 1 False
[218 159 173] 1 1 True
[218 159 174] 1 1 True
[218 159 175] 0 1 False
[218 160 172] 1 0 False
[218 160 173] 1 1 True
[218 160 174] 1 0 False
[218 160 175] 1 1 True
[218 160 176] 1 0 False
[218 161 172] 0 1 False
[218 161 173] 1 1 True
[218 161

[219  69 139] 0 1 False
[219  69 140] 1 1 True
[219  69 141] 1 1 True
[219  69 142] 0 1 False
[219  69 143] 1 1 True
[219  69 144] 1 1 True
[219  69 145] 0 1 False
[219  69 147] 1 1 True
[219  69 148] 1 1 True
[219  69 149] 1 1 True
[219  69 150] 1 1 True
[219  69 151] 1 1 True
[219  70 139] 1 1 True
[219  70 140] 1 1 True
[219  70 141] 0 1 False
[219  70 142] 0 1 False
[219  70 143] 0 1 False
[219  70 145] 0 1 False
[219  70 147] 1 1 True
[219  70 148] 1 1 True
[219  70 149] 1 1 True
[219  70 150] 1 1 True
[219  70 151] 1 1 True
[219  71 138] 1 0 False
[219  71 139] 0 1 False
[219  71 140] 0 1 False
[219  71 141] 1 0 False
[219  71 142] 0 1 False
[219  71 146] 1 1 True
[219  71 148] 1 1 True
[219  71 149] 1 1 True
[219  71 150] 1 1 True
[219  72   2] 0 1 False
[219  72 139] 1 1 True
[219  72 147] 1 1 True
[219  72 148] 0 1 False
[219  72 149] 1 1 True
[219  72 150] 1 1 True
[219  72 151] 1 0 False
[219  73 137] 0 1 False
[219  73 138] 1 1 True
[219  73 139] 1 0 False
[219  73 140] 1 1

[220  42  48] 1 0 False
[220  44  98] 1 0 False
[220  45   8] 0 1 False
[220  45  80] 1 0 False
[220  46  14] 1 0 False
[220  46 131] 0 1 False
[220  46 141] 1 1 True
[220  47 132] 1 0 False
[220  48 143] 0 1 False
[220  48 144] 1 0 False
[220  49 143] 0 1 False
[220  50  46] 0 1 False
[220  51 144] 1 0 False
[220  53  38] 0 1 False
[220  53  88] 1 0 False
[220  54 146] 0 1 False
[220  55 105] 1 0 False
[220  55 143] 1 0 False
[220  55 144] 1 1 True
[220  55 145] 1 1 True
[220  55 146] 1 1 True
[220  56  96] 1 0 False
[220  56 143] 0 1 False
[220  56 144] 1 0 False
[220  56 145] 1 1 True
[220  56 146] 1 1 True
[220  57 146] 1 1 True
[220  57 147] 1 1 True
[220  58 103] 0 1 False
[220  58 112] 0 1 False
[220  58 146] 0 1 False
[220  59 113] 1 0 False
[220  60 130] 1 0 False
[220  60 142] 0 1 False
[220  60 146] 0 1 False
[220  60 147] 0 1 False
[220  60 148] 1 0 False
[220  61  26] 0 1 False
[220  61  76] 1 0 False
[220  61 118] 1 0 False
[220  61 135] 0 1 False
[220  61 137] 1 0 False


[220 228 140] 1 0 False
[220 228 189] 0 1 False
[220 228 190] 1 1 True
[220 228 191] 0 1 False
[220 228 192] 1 1 True
[220 228 193] 1 1 True
[220 228 194] 1 1 True
[220 228 195] 1 1 True
[220 228 196] 0 1 False
[220 229 139] 1 1 True
[220 229 140] 1 1 True
[220 230 139] 1 0 False
[220 230 140] 1 1 True
[220 231 140] 0 1 False
[220 231 141] 1 0 False
[220 231 193] 1 0 False
[220 232 138] 1 0 False
[220 232 139] 0 1 False
[220 233 100] 0 1 False
[220 233 144] 1 0 False
[220 235  85] 0 1 False
[220 236  85] 1 0 False
[220 237 119] 0 1 False
[220 241 118] 0 1 False
[220 241 165] 0 1 False
[220 241 206] 1 1 True
[220 242 165] 1 0 False
[220 242 206] 1 0 False
[220 243 204] 1 0 False
[220 244 156] 1 0 False
[220 245  81] 1 0 False
[220 245  82] 1 0 False
[220 245 149] 0 1 False
[220 245 150] 0 1 False
[220 246 151] 0 1 False
[220 250 187] 1 0 False
[220 256 187] 0 1 False
[220 257 186] 0 1 False
[220 257 209] 0 1 False
[220 258 157] 0 1 False
[220 258 158] 0 1 False
[220 262  97] 1 1 True
[2

[221  87 161] 1 1 True
[221  88 147] 1 0 False
[221  88 148] 1 1 True
[221  88 149] 0 1 False
[221  88 150] 1 1 True
[221  88 151] 0 1 False
[221  88 155] 0 1 False
[221  88 161] 0 1 False
[221  88 162] 1 1 True
[221  89 127] 0 1 False
[221  89 161] 1 1 True
[221  89 162] 0 1 False
[221  91 119] 1 0 False
[221  92  67] 1 1 True
[221  93 161] 0 1 False
[221  94 158] 0 1 False
[221  94 159] 1 0 False
[221  94 160] 1 1 True
[221  95 161] 1 0 False
[221  96 103] 1 0 False
[221  96 160] 1 1 True
[221  96 161] 1 1 True
[221  96 162] 1 1 True
[221  97 105] 1 1 True
[221  98 138] 0 1 False
[221  99 138] 1 0 False
[221 104 128] 1 0 False
[221 105 120] 0 1 False
[221 106 118] 0 1 False
[221 106 119] 0 1 False
[221 106 120] 0 1 False
[221 106 139] 1 1 True
[221 106 167] 0 1 False
[221 108 169] 0 1 False
[221 110  94] 0 1 False
[221 110 170] 1 0 False
[221 112  92] 1 0 False
[221 112 171] 1 1 True
[221 113 139] 1 0 False
[221 116  92] 0 1 False
[221 116 152] 1 1 True
[221 116 153] 1 1 True
[221 11

[222  64 138] 1 1 True
[222  64 139] 1 1 True
[222  64 140] 1 1 True
[222  64 141] 1 1 True
[222  64 142] 1 1 True
[222  64 143] 1 1 True
[222  64 144] 1 1 True
[222  64 145] 1 1 True
[222  64 147] 1 1 True
[222  64 148] 1 1 True
[222  64 149] 1 1 True
[222  64 150] 1 1 True
[222  64 151] 1 1 True
[222  65  26] 1 1 True
[222  65  27] 0 1 False
[222  65  66] 0 1 False
[222  65 136] 0 1 False
[222  65 137] 1 1 True
[222  65 139] 1 1 True
[222  65 140] 1 1 True
[222  65 141] 1 1 True
[222  65 142] 1 1 True
[222  65 143] 0 1 False
[222  65 144] 1 1 True
[222  65 145] 1 1 True
[222  65 146] 1 1 True
[222  65 147] 1 1 True
[222  65 148] 1 1 True
[222  65 149] 1 1 True
[222  65 150] 1 1 True
[222  65 151] 1 1 True
[222  66  67] 1 0 False
[222  66 137] 1 0 False
[222  66 138] 1 0 False
[222  66 139] 1 1 True
[222  66 140] 1 1 True
[222  66 141] 1 1 True
[222  66 142] 1 1 True
[222  66 143] 1 1 True
[222  66 144] 1 1 True
[222  66 145] 1 1 True
[222  66 146] 1 1 True
[222  66 147] 1 1 True
[222

[223  15 107] 1 0 False
[223  15 117] 1 0 False
[223  16  61] 1 1 True
[223  16  63] 0 1 False
[223  16  64] 1 1 True
[223  16  65] 1 1 True
[223  16  66] 1 1 True
[223  16  67] 1 1 True
[223  16  68] 1 1 True
[223  16 107] 0 1 False
[223  16 108] 0 1 False
[223  16 110] 1 1 True
[223  16 117] 1 0 False
[223  17  64] 1 0 False
[223  17  65] 0 1 False
[223  17  66] 1 0 False
[223  17  68] 1 1 True
[223  17 106] 0 1 False
[223  17 108] 0 1 False
[223  17 117] 0 1 False
[223  18 116] 1 0 False
[223  19 114] 1 0 False
[223  19 115] 1 1 True
[223  19 119] 0 1 False
[223  19 121] 1 1 True
[223  20  39] 1 0 False
[223  20  41] 0 1 False
[223  20  66] 0 1 False
[223  20  98] 1 1 True
[223  20 120] 0 1 False
[223  21  41] 0 1 False
[223  21  42] 0 1 False
[223  21  68] 1 0 False
[223  21  97] 1 0 False
[223  21  98] 1 1 True
[223  22  11] 0 1 False
[223  22  12] 1 1 True
[223  22  13] 1 0 False
[223  22  19] 0 1 False
[223  23  12] 1 1 True
[223  23  13] 1 1 True
[223  23  20] 1 0 False
[223  2

[223 173 145] 1 0 False
[223 173 146] 0 1 False
[223 174 134] 0 1 False
[223 177 120] 0 1 False
[223 180 169] 0 1 False
[223 180 170] 1 1 True
[223 180 209] 1 0 False
[223 181 169] 0 1 False
[223 183 161] 1 0 False
[223 184 172] 0 1 False
[223 185 117] 1 1 True
[223 193  77] 0 1 False
[223 194  78] 0 1 False
[223 195 186] 0 1 False
[223 196 125] 1 0 False
[223 197 126] 1 1 True
[223 198 125] 0 1 False
[223 198 126] 1 1 True
[223 200 140] 1 1 True
[223 202  92] 0 1 False
[223 205 203] 1 1 True
[223 207 172] 0 1 False
[223 208 172] 1 0 False
[223 209 135] 0 1 False
[223 209 172] 1 1 True
[223 209 173] 0 1 False
[223 210  71] 0 1 False
[223 210  72] 0 1 False
[223 211  78] 1 0 False
[223 213  67] 1 1 True
[223 214  67] 0 1 False
[223 214 131] 1 0 False
[223 222 204] 1 0 False
[223 224  89] 1 0 False
[223 224  90] 1 1 True
[223 224 204] 1 1 True
[223 224 205] 1 0 False
[223 225 193] 0 1 False
[223 225 194] 0 1 False
[223 225 203] 1 1 True
[223 225 204] 1 1 True
[223 226 157] 1 1 True
[223 

[224  84 152] 1 1 True
[224  84 153] 1 1 True
[224  84 154] 1 1 True
[224  84 155] 1 1 True
[224  84 156] 1 0 False
[224  84 160] 1 1 True
[224  84 161] 1 1 True
[224  85 150] 1 1 True
[224  85 151] 0 1 False
[224  85 152] 1 1 True
[224  85 153] 1 1 True
[224  85 154] 1 1 True
[224  85 155] 1 1 True
[224  85 156] 1 1 True
[224  85 161] 1 1 True
[224  86 148] 0 1 False
[224  86 149] 1 1 True
[224  86 150] 1 1 True
[224  86 151] 1 1 True
[224  86 154] 1 1 True
[224  86 155] 0 1 False
[224  86 156] 1 0 False
[224  86 157] 0 1 False
[224  86 159] 1 1 True
[224  86 160] 1 1 True
[224  86 161] 1 1 True
[224  87 148] 1 1 True
[224  87 149] 1 1 True
[224  87 150] 1 0 False
[224  87 152] 0 1 False
[224  87 159] 1 1 True
[224  87 160] 1 1 True
[224  87 161] 1 1 True
[224  88 147] 1 1 True
[224  88 148] 1 1 True
[224  88 149] 0 1 False
[224  88 150] 1 1 True
[224  88 162] 1 0 False
[224  89 161] 1 1 True
[224  90 127] 0 1 False
[224  91 119] 1 0 False
[224  92  67] 1 1 True
[224  94 158] 0 1 Fals

[225  66 137] 1 1 True
[225  66 138] 1 0 False
[225  66 139] 1 1 True
[225  66 140] 1 1 True
[225  66 141] 1 1 True
[225  66 142] 1 1 True
[225  66 143] 1 1 True
[225  66 144] 1 1 True
[225  66 145] 1 0 False
[225  66 146] 1 1 True
[225  66 147] 1 1 True
[225  66 148] 1 1 True
[225  66 149] 1 1 True
[225  66 150] 1 1 True
[225  66 151] 1 1 True
[225  66 152] 1 1 True
[225  67 138] 1 0 False
[225  67 139] 0 1 False
[225  67 140] 1 1 True
[225  67 141] 1 1 True
[225  67 142] 1 1 True
[225  67 143] 1 1 True
[225  67 144] 1 1 True
[225  67 145] 1 1 True
[225  67 146] 1 1 True
[225  67 147] 1 1 True
[225  67 149] 1 0 False
[225  67 150] 0 1 False
[225  67 151] 0 1 False
[225  67 152] 1 1 True
[225  68  99] 0 1 False
[225  68 140] 0 1 False
[225  68 141] 1 1 True
[225  68 142] 1 1 True
[225  68 144] 1 1 True
[225  68 145] 1 1 True
[225  68 146] 1 1 True
[225  68 147] 1 1 True
[225  68 148] 1 1 True
[225  68 149] 1 1 True
[225  68 150] 1 1 True
[225  68 151] 0 1 False
[225  68 152] 1 0 False


[226   9 101] 1 1 True
[226  10 101] 0 1 False
[226  10 102] 1 0 False
[226  10 103] 1 0 False
[226  11  69] 1 0 False
[226  11 102] 1 0 False
[226  11 103] 1 1 True
[226  13  67] 0 1 False
[226  13  68] 1 0 False
[226  13  69] 0 1 False
[226  14  64] 0 1 False
[226  14  65] 1 0 False
[226  14  67] 0 1 False
[226  14  68] 1 1 True
[226  14  69] 1 1 True
[226  14  70] 1 0 False
[226  14 104] 1 0 False
[226  15  64] 1 1 True
[226  15  65] 0 1 False
[226  15  66] 1 1 True
[226  15  67] 1 1 True
[226  15  68] 1 1 True
[226  15  69] 1 1 True
[226  15 105] 1 1 True
[226  15 106] 1 1 True
[226  15 107] 1 1 True
[226  15 117] 1 0 False
[226  16  61] 1 1 True
[226  16  64] 1 1 True
[226  16  65] 1 1 True
[226  16  66] 1 1 True
[226  16  67] 1 0 False
[226  16  68] 1 1 True
[226  16 106] 0 1 False
[226  16 107] 0 1 False
[226  16 108] 0 1 False
[226  16 110] 1 1 True
[226  16 117] 1 0 False
[226  17  64] 1 1 True
[226  17  66] 1 0 False
[226  17  67] 0 1 False
[226  17  68] 1 1 True
[226  17 112

[226 146  98] 1 1 True
[226 146 115] 0 1 False
[226 146 116] 0 1 False
[226 146 117] 1 1 True
[226 147 113] 1 0 False
[226 147 115] 1 1 True
[226 147 117] 1 0 False
[226 147 118] 1 1 True
[226 147 165] 1 1 True
[226 148  77] 0 1 False
[226 148  78] 1 1 True
[226 148  79] 0 1 False
[226 148 114] 1 1 True
[226 148 115] 1 1 True
[226 148 116] 1 0 False
[226 148 117] 0 1 False
[226 148 151] 1 0 False
[226 149  76] 1 0 False
[226 149  77] 0 1 False
[226 149 118] 1 0 False
[226 149 119] 0 1 False
[226 150 113] 0 1 False
[226 151 112] 0 1 False
[226 152 168] 1 1 True
[226 158 118] 1 0 False
[226 159 126] 0 1 False
[226 159 173] 1 1 True
[226 159 174] 1 1 True
[226 160 172] 1 0 False
[226 160 173] 1 1 True
[226 160 174] 1 1 True
[226 160 175] 1 1 True
[226 160 176] 1 0 False
[226 161 173] 1 1 True
[226 161 174] 1 0 False
[226 162 173] 1 1 True
[226 162 174] 1 1 True
[226 163 173] 0 1 False
[226 163 174] 0 1 False
[226 163 175] 1 0 False
[226 164 161] 0 1 False
[226 164 173] 1 1 True
[226 164 1

[227  74 141] 1 1 True
[227  74 142] 0 1 False
[227  74 149] 1 0 False
[227  74 150] 1 1 True
[227  74 151] 0 1 False
[227  74 152] 1 1 True
[227  74 153] 1 1 True
[227  75 140] 0 1 False
[227  75 152] 1 1 True
[227  75 153] 1 1 True
[227  76  29] 1 1 True
[227  76 151] 0 1 False
[227  76 152] 1 1 True
[227  76 153] 1 1 True
[227  76 158] 0 1 False
[227  77  29] 0 1 False
[227  77 151] 1 1 True
[227  77 152] 1 1 True
[227  77 153] 1 1 True
[227  77 154] 1 1 True
[227  77 155] 1 0 False
[227  77 158] 0 1 False
[227  77 159] 1 1 True
[227  78 146] 0 1 False
[227  78 152] 1 1 True
[227  78 153] 1 1 True
[227  78 154] 1 1 True
[227  78 155] 1 1 True
[227  78 156] 1 0 False
[227  78 157] 0 1 False
[227  78 158] 0 1 False
[227  78 159] 1 1 True
[227  78 160] 1 0 False
[227  79 149] 1 0 False
[227  79 151] 0 1 False
[227  79 152] 1 1 True
[227  79 153] 1 1 True
[227  79 154] 1 1 True
[227  79 155] 1 1 True
[227  79 158] 0 1 False
[227  80 103] 1 1 True
[227  80 152] 1 1 True
[227  80 153] 1 1

[228  63  55] 0 1 False
[228  63 114] 0 1 False
[228  63 136] 1 0 False
[228  63 137] 1 0 False
[228  63 139] 1 1 True
[228  63 140] 1 0 False
[228  63 141] 1 0 False
[228  63 142] 1 0 False
[228  63 143] 1 1 True
[228  63 144] 1 1 True
[228  63 145] 0 1 False
[228  63 147] 1 1 True
[228  63 148] 1 1 True
[228  63 149] 1 1 True
[228  63 150] 1 1 True
[228  64  26] 0 1 False
[228  64 128] 0 1 False
[228  64 134] 1 1 True
[228  64 135] 0 1 False
[228  64 136] 1 1 True
[228  64 137] 1 1 True
[228  64 138] 1 1 True
[228  64 139] 1 1 True
[228  64 140] 1 1 True
[228  64 141] 1 1 True
[228  64 142] 1 1 True
[228  64 143] 1 1 True
[228  64 144] 1 1 True
[228  64 145] 1 1 True
[228  64 146] 0 1 False
[228  64 147] 1 0 False
[228  64 148] 1 1 True
[228  64 149] 1 1 True
[228  64 150] 1 1 True
[228  64 151] 1 1 True
[228  65  26] 1 1 True
[228  65 132] 0 1 False
[228  65 136] 0 1 False
[228  65 137] 1 1 True
[228  65 139] 1 1 True
[228  65 140] 1 1 True
[228  65 141] 1 1 True
[228  65 142] 1 1 T

[228 262  96] 0 1 False
[228 262  97] 1 0 False
[228 263  96] 1 0 False
[228 269 184] 1 0 False
[228 269 185] 0 1 False
[228 270 184] 1 1 True
[228 270 185] 0 1 False
[228 273 171] 0 1 False
[228 287 142] 0 1 False
[228 287 143] 0 1 False
[228 287 144] 0 1 False
[228 290 127] 1 1 True
[228 290 155] 0 1 False
[228 291 225] 0 1 False
[229   0  99] 0 1 False
[229   5  39] 0 1 False
[229   5  45] 1 1 True
[229   6  48] 1 1 True
[229   8  60] 0 1 False
[229   9 101] 1 1 True
[229  10 102] 1 1 True
[229  10 103] 1 0 False
[229  11  69] 1 0 False
[229  11 102] 1 0 False
[229  11 103] 1 0 False
[229  12  59] 0 1 False
[229  13  68] 1 0 False
[229  13  85] 0 1 False
[229  13  86] 0 1 False
[229  14  64] 0 1 False
[229  14  65] 1 1 True
[229  14  66] 0 1 False
[229  14  67] 0 1 False
[229  14  68] 1 1 True
[229  14  69] 1 1 True
[229  14  70] 1 1 True
[229  14 104] 1 0 False
[229  15  63] 0 1 False
[229  15  64] 1 1 True
[229  15  65] 0 1 False
[229  15  66] 1 1 True
[229  15  67] 1 1 True
[229 

[229  97 105] 1 1 True
[229  99 105] 0 1 False
[229  99 138] 1 0 False
[229 102 165] 0 1 False
[229 104 128] 1 0 False
[229 104 164] 0 1 False
[229 106 118] 0 1 False
[229 106 119] 0 1 False
[229 106 120] 0 1 False
[229 106 139] 1 1 True
[229 107 165] 0 1 False
[229 110 170] 1 0 False
[229 111  93] 0 1 False
[229 112  92] 1 0 False
[229 112 171] 1 1 True
[229 113 139] 1 0 False
[229 116 143] 0 1 False
[229 116 152] 1 1 True
[229 116 153] 1 0 False
[229 117  68] 0 1 False
[229 117 143] 1 0 False
[229 117 151] 0 1 False
[229 117 152] 1 1 True
[229 117 153] 0 1 False
[229 117 154] 1 1 True
[229 118 151] 1 0 False
[229 118 152] 1 1 True
[229 118 153] 1 0 False
[229 119 152] 1 0 False
[229 123 141] 0 1 False
[229 124 141] 0 1 False
[229 124 175] 1 0 False
[229 130 148] 1 0 False
[229 130 153] 1 0 False
[229 132 153] 1 1 True
[229 133 153] 1 0 False
[229 134 139] 0 1 False
[229 135 197] 0 1 False
[229 141 160] 1 1 True
[229 142 129] 0 1 False
[229 144 116] 0 1 False
[229 145 115] 1 0 False
[

[230  70 142] 0 1 False
[230  70 143] 0 1 False
[230  70 145] 0 1 False
[230  70 147] 1 1 True
[230  70 148] 1 1 True
[230  70 149] 1 1 True
[230  70 150] 1 1 True
[230  70 151] 1 1 True
[230  71 138] 1 0 False
[230  71 140] 0 1 False
[230  71 141] 1 0 False
[230  71 146] 1 1 True
[230  71 148] 1 1 True
[230  71 149] 1 1 True
[230  71 150] 1 1 True
[230  72 139] 1 1 True
[230  72 140] 0 1 False
[230  72 147] 1 1 True
[230  72 149] 1 0 False
[230  72 150] 1 1 True
[230  72 151] 1 1 True
[230  73 137] 0 1 False
[230  73 138] 1 1 True
[230  73 139] 1 0 False
[230  73 140] 1 1 True
[230  73 141] 1 1 True
[230  73 147] 0 1 False
[230  73 149] 1 0 False
[230  73 150] 1 1 True
[230  73 153] 1 1 True
[230  73 154] 1 1 True
[230  74 137] 1 0 False
[230  74 141] 1 1 True
[230  74 142] 0 1 False
[230  74 149] 1 0 False
[230  74 150] 1 1 True
[230  74 152] 1 1 True
[230  74 153] 1 1 True
[230  75 140] 0 1 False
[230  75 152] 1 1 True
[230  75 153] 1 1 True
[230  76  28] 0 1 False
[230  76  29] 1 1

[231  56 134] 0 1 False
[231  56 143] 0 1 False
[231  56 144] 1 1 True
[231  56 145] 1 1 True
[231  56 146] 1 1 True
[231  56 147] 0 1 False
[231  57 143] 0 1 False
[231  57 146] 1 1 True
[231  57 147] 1 1 True
[231  58 112] 0 1 False
[231  58 146] 0 1 False
[231  59 112] 0 1 False
[231  59 113] 1 0 False
[231  60  65] 0 1 False
[231  60  72] 0 1 False
[231  60 130] 1 0 False
[231  60 142] 0 1 False
[231  60 148] 1 1 True
[231  61  26] 0 1 False
[231  61  76] 1 0 False
[231  61 118] 1 0 False
[231  61 132] 0 1 False
[231  61 137] 1 1 True
[231  61 142] 1 1 True
[231  61 143] 0 1 False
[231  61 146] 1 1 True
[231  61 147] 1 1 True
[231  61 148] 1 1 True
[231  61 149] 0 1 False
[231  62 134] 0 1 False
[231  62 137] 1 0 False
[231  62 138] 0 1 False
[231  62 140] 0 1 False
[231  62 142] 1 1 True
[231  62 143] 1 1 True
[231  62 145] 1 1 True
[231  62 147] 1 1 True
[231  62 148] 1 1 True
[231  62 149] 1 1 True
[231  63 114] 0 1 False
[231  63 136] 1 0 False
[231  63 137] 1 0 False
[231  63 

[231 228 195] 1 1 True
[231 229 139] 1 1 True
[231 229 140] 1 1 True
[231 230 139] 1 1 True
[231 230 140] 1 1 True
[231 231  94] 0 1 False
[231 231 140] 0 1 False
[231 231 141] 1 0 False
[231 231 193] 1 1 True
[231 232 138] 1 0 False
[231 233 100] 0 1 False
[231 233 144] 1 0 False
[231 236  85] 1 1 True
[231 237 119] 0 1 False
[231 240 206] 0 1 False
[231 241 206] 1 1 True
[231 242 165] 1 0 False
[231 242 204] 0 1 False
[231 242 206] 1 0 False
[231 243 204] 1 0 False
[231 243 205] 0 1 False
[231 244 156] 1 0 False
[231 245  81] 1 1 True
[231 245  82] 1 1 True
[231 246 150] 0 1 False
[231 250  98] 0 1 False
[231 250 187] 1 0 False
[231 256 187] 0 1 False
[231 258  76] 0 1 False
[231 258 157] 0 1 False
[231 258 158] 0 1 False
[231 258 159] 0 1 False
[231 259 111] 0 1 False
[231 260  97] 0 1 False
[231 262  97] 1 1 True
[231 263  96] 1 1 True
[231 269 184] 1 1 True
[231 270 183] 0 1 False
[231 270 184] 1 1 True
[231 280 153] 0 1 False
[231 286 143] 0 1 False
[231 287 126] 0 1 False
[231 2

[232  93 160] 0 1 False
[232  94 158] 0 1 False
[232  94 159] 1 1 True
[232  94 160] 1 1 True
[232  95 161] 1 1 True
[232  96 103] 1 0 False
[232  96 105] 0 1 False
[232  96 160] 1 1 True
[232  96 161] 1 1 True
[232  96 162] 1 0 False
[232  97 105] 1 1 True
[232  99 138] 1 0 False
[232 101  68] 0 1 False
[232 104 128] 1 1 True
[232 104 165] 0 1 False
[232 106 119] 0 1 False
[232 106 120] 0 1 False
[232 106 121] 0 1 False
[232 106 139] 1 1 True
[232 106 165] 0 1 False
[232 106 166] 0 1 False
[232 107 165] 0 1 False
[232 110 170] 1 0 False
[232 112  92] 1 1 True
[232 112 171] 1 1 True
[232 113 139] 1 0 False
[232 116 143] 0 1 False
[232 116 152] 1 1 True
[232 116 153] 1 0 False
[232 117 143] 1 0 False
[232 117 151] 0 1 False
[232 117 152] 1 1 True
[232 117 153] 0 1 False
[232 117 154] 1 0 False
[232 117 173] 0 1 False
[232 118 151] 1 0 False
[232 118 152] 1 1 True
[232 118 153] 1 1 True
[232 119 152] 1 0 False
[232 124 141] 0 1 False
[232 124 175] 1 0 False
[232 125 175] 0 1 False
[232 1

[233  69 151] 1 0 False
[233  70 139] 1 1 True
[233  70 140] 1 0 False
[233  70 141] 0 1 False
[233  70 142] 0 1 False
[233  70 143] 0 1 False
[233  70 145] 0 1 False
[233  70 147] 1 1 True
[233  70 148] 1 1 True
[233  70 149] 1 1 True
[233  70 150] 1 1 True
[233  70 151] 1 0 False
[233  71 138] 1 0 False
[233  71 139] 0 1 False
[233  71 140] 0 1 False
[233  71 141] 1 0 False
[233  71 142] 0 1 False
[233  71 146] 1 1 True
[233  71 148] 1 1 True
[233  71 149] 1 1 True
[233  71 150] 1 1 True
[233  72 138] 0 1 False
[233  72 139] 1 1 True
[233  72 146] 0 1 False
[233  72 147] 1 1 True
[233  72 148] 0 1 False
[233  72 149] 1 1 True
[233  72 150] 1 1 True
[233  72 151] 1 1 True
[233  73 138] 1 1 True
[233  73 139] 1 0 False
[233  73 140] 1 1 True
[233  73 141] 1 0 False
[233  73 149] 1 1 True
[233  73 150] 1 1 True
[233  73 152] 0 1 False
[233  73 153] 1 1 True
[233  73 154] 1 1 True
[233  74 137] 1 0 False
[233  74 138] 0 1 False
[233  74 141] 1 1 True
[233  74 142] 0 1 False
[233  74 149]

[234  51 144] 1 0 False
[234  53  38] 0 1 False
[234  53  88] 1 0 False
[234  55 105] 1 0 False
[234  55 143] 1 0 False
[234  55 144] 1 1 True
[234  55 145] 1 0 False
[234  55 146] 1 1 True
[234  56  36] 0 1 False
[234  56  96] 1 0 False
[234  56 142] 0 1 False
[234  56 143] 0 1 False
[234  56 144] 1 1 True
[234  56 145] 1 0 False
[234  56 146] 1 1 True
[234  56 147] 0 1 False
[234  57 146] 1 1 True
[234  57 147] 1 1 True
[234  59  79] 0 1 False
[234  59 112] 0 1 False
[234  59 113] 1 0 False
[234  60 130] 1 0 False
[234  60 142] 0 1 False
[234  60 146] 0 1 False
[234  60 147] 0 1 False
[234  60 148] 1 1 True
[234  61  38] 0 1 False
[234  61  76] 1 0 False
[234  61 117] 0 1 False
[234  61 118] 1 0 False
[234  61 130] 0 1 False
[234  61 137] 1 1 True
[234  61 142] 1 0 False
[234  61 146] 1 1 True
[234  61 147] 1 1 True
[234  61 148] 1 1 True
[234  62 113] 0 1 False
[234  62 134] 0 1 False
[234  62 137] 1 1 True
[234  62 139] 0 1 False
[234  62 140] 0 1 False
[234  62 142] 1 1 True
[234 

[234 211  78] 1 0 False
[234 213  67] 1 0 False
[234 213 186] 0 1 False
[234 214 131] 1 0 False
[234 214 186] 0 1 False
[234 217 104] 0 1 False
[234 221  97] 0 1 False
[234 222 204] 1 0 False
[234 223  90] 0 1 False
[234 224  89] 1 0 False
[234 224  90] 1 1 True
[234 224 204] 1 1 True
[234 224 205] 1 0 False
[234 225 203] 1 1 True
[234 225 204] 1 1 True
[234 226 157] 1 1 True
[234 226 194] 0 1 False
[234 226 203] 1 0 False
[234 226 204] 1 0 False
[234 226 205] 1 1 True
[234 227 191] 0 1 False
[234 227 192] 0 1 False
[234 227 194] 1 1 True
[234 227 195] 1 1 True
[234 227 197] 0 1 False
[234 228 139] 0 1 False
[234 228 140] 1 0 False
[234 228 190] 1 0 False
[234 228 191] 0 1 False
[234 228 192] 1 1 True
[234 228 193] 1 1 True
[234 228 194] 1 1 True
[234 228 195] 1 1 True
[234 228 196] 0 1 False
[234 229 139] 1 1 True
[234 229 140] 1 1 True
[234 230 139] 1 1 True
[234 230 140] 1 1 True
[234 231 141] 1 0 False
[234 231 193] 1 0 False
[234 232 138] 1 0 False
[234 233 144] 1 0 False
[234 236

[235  80 156] 1 1 True
[235  80 157] 0 1 False
[235  80 159] 1 0 False
[235  80 160] 1 1 True
[235  81 153] 1 1 True
[235  81 154] 1 1 True
[235  81 155] 1 1 True
[235  81 156] 1 1 True
[235  81 158] 0 1 False
[235  81 159] 0 1 False
[235  81 160] 0 1 False
[235  82 153] 1 1 True
[235  82 154] 1 1 True
[235  82 155] 1 1 True
[235  82 156] 1 1 True
[235  82 157] 0 1 False
[235  82 158] 1 1 True
[235  82 159] 1 1 True
[235  82 160] 0 1 False
[235  82 161] 1 1 True
[235  83 130] 0 1 False
[235  83 152] 0 1 False
[235  83 153] 1 0 False
[235  83 154] 0 1 False
[235  83 155] 1 1 True
[235  83 160] 0 1 False
[235  83 161] 1 1 True
[235  84 152] 1 1 True
[235  84 153] 1 1 True
[235  84 154] 1 1 True
[235  84 155] 1 1 True
[235  84 156] 1 0 False
[235  84 157] 0 1 False
[235  84 160] 1 1 True
[235  84 161] 1 1 True
[235  85  50] 0 1 False
[235  85 150] 1 1 True
[235  85 151] 0 1 False
[235  85 152] 1 0 False
[235  85 153] 1 1 True
[235  85 154] 1 1 True
[235  85 155] 1 1 True
[235  85 156] 1 0

[236  63 139] 1 0 False
[236  63 140] 1 1 True
[236  63 141] 1 1 True
[236  63 142] 1 1 True
[236  63 143] 1 1 True
[236  63 144] 1 1 True
[236  63 147] 1 1 True
[236  63 148] 1 1 True
[236  63 149] 1 1 True
[236  63 150] 1 0 False
[236  64  26] 0 1 False
[236  64 134] 1 1 True
[236  64 136] 1 1 True
[236  64 137] 1 1 True
[236  64 138] 1 1 True
[236  64 139] 1 1 True
[236  64 140] 1 1 True
[236  64 141] 1 1 True
[236  64 142] 1 1 True
[236  64 143] 1 1 True
[236  64 144] 1 1 True
[236  64 145] 1 1 True
[236  64 146] 0 1 False
[236  64 147] 1 1 True
[236  64 148] 1 1 True
[236  64 149] 1 1 True
[236  64 150] 1 1 True
[236  64 151] 1 1 True
[236  65  15] 0 1 False
[236  65  26] 1 1 True
[236  65  27] 0 1 False
[236  65  66] 0 1 False
[236  65 137] 1 1 True
[236  65 139] 1 1 True
[236  65 140] 1 1 True
[236  65 141] 1 1 True
[236  65 142] 1 1 True
[236  65 144] 1 1 True
[236  65 145] 1 1 True
[236  65 146] 1 1 True
[236  65 147] 1 1 True
[236  65 148] 1 1 True
[236  65 149] 1 1 True
[236

[236 232 138] 1 1 True
[236 233 144] 1 0 False
[236 236  85] 1 1 True
[236 241 138] 0 1 False
[236 241 206] 1 1 True
[236 242 165] 1 1 True
[236 242 204] 0 1 False
[236 242 206] 1 0 False
[236 243 204] 1 0 False
[236 244  81] 0 1 False
[236 244 156] 1 0 False
[236 245  81] 1 1 True
[236 245  82] 1 1 True
[236 245 150] 0 1 False
[236 246 150] 0 1 False
[236 248 144] 0 1 False
[236 250 187] 1 0 False
[236 256 186] 0 1 False
[236 256 187] 0 1 False
[236 257 209] 0 1 False
[236 258 157] 0 1 False
[236 258 158] 0 1 False
[236 258 209] 0 1 False
[236 262  97] 1 1 True
[236 263  96] 1 0 False
[236 269 184] 1 1 True
[236 270 184] 1 1 True
[236 280 153] 0 1 False
[236 287 125] 0 1 False
[236 287 142] 0 1 False
[236 287 143] 0 1 False
[236 290 127] 1 0 False
[236 292 168] 0 1 False
[237   1  19] 0 1 False
[237   1  23] 0 1 False
[237   5  11] 0 1 False
[237   5  45] 1 0 False
[237   5  46] 0 1 False
[237   6  48] 1 0 False
[237   6  71] 0 1 False
[237   8  60] 0 1 False
[237   8  71] 0 1 False
[

[237 106 166] 0 1 False
[237 107 167] 0 1 False
[237 107 168] 0 1 False
[237 108 169] 0 1 False
[237 110 170] 1 0 False
[237 112  92] 1 1 True
[237 112 171] 1 1 True
[237 113 139] 1 0 False
[237 116 142] 0 1 False
[237 116 143] 0 1 False
[237 116 151] 0 1 False
[237 116 152] 1 1 True
[237 116 153] 1 1 True
[237 117 143] 1 0 False
[237 117 151] 0 1 False
[237 117 152] 1 1 True
[237 117 153] 0 1 False
[237 117 154] 1 1 True
[237 117 173] 0 1 False
[237 118 151] 1 1 True
[237 118 152] 1 1 True
[237 118 153] 1 0 False
[237 119 152] 1 1 True
[237 122 115] 0 1 False
[237 123 141] 0 1 False
[237 123 142] 0 1 False
[237 124 141] 0 1 False
[237 124 142] 0 1 False
[237 124 175] 1 0 False
[237 125 113] 0 1 False
[237 126 114] 0 1 False
[237 130 148] 1 0 False
[237 130 153] 1 0 False
[237 131  96] 0 1 False
[237 132 153] 1 1 True
[237 133 153] 1 0 False
[237 141 160] 1 1 True
[237 145 114] 0 1 False
[237 145 115] 1 1 True
[237 145 116] 0 1 False
[237 145 117] 1 1 True
[237 146  98] 1 0 False
[237 

[238  70 145] 0 1 False
[238  70 147] 1 1 True
[238  70 148] 1 1 True
[238  70 149] 1 1 True
[238  70 150] 1 1 True
[238  70 151] 1 0 False
[238  71 138] 1 0 False
[238  71 139] 0 1 False
[238  71 140] 0 1 False
[238  71 141] 1 1 True
[238  71 146] 1 1 True
[238  71 148] 1 1 True
[238  71 149] 1 1 True
[238  71 150] 1 1 True
[238  72   2] 0 1 False
[238  72 139] 1 0 False
[238  72 140] 0 1 False
[238  72 147] 1 0 False
[238  72 148] 0 1 False
[238  72 149] 1 0 False
[238  72 150] 1 1 True
[238  72 151] 1 0 False
[238  73 138] 1 1 True
[238  73 139] 1 1 True
[238  73 140] 1 1 True
[238  73 141] 1 1 True
[238  73 149] 1 0 False
[238  73 150] 1 1 True
[238  73 152] 0 1 False
[238  73 153] 1 1 True
[238  73 154] 1 1 True
[238  74 137] 1 0 False
[238  74 138] 0 1 False
[238  74 141] 1 1 True
[238  74 149] 1 0 False
[238  74 150] 1 1 True
[238  74 151] 0 1 False
[238  74 152] 1 0 False
[238  74 153] 1 1 True
[238  75 152] 1 1 True
[238  75 153] 1 1 True
[238  76  29] 1 1 True
[238  76 143] 0

[239  51 144] 1 1 True
[239  53  38] 0 1 False
[239  53  88] 1 0 False
[239  54 133] 0 1 False
[239  55 105] 1 0 False
[239  55 143] 1 0 False
[239  55 144] 1 1 True
[239  55 145] 1 1 True
[239  55 146] 1 1 True
[239  56  96] 1 0 False
[239  56 144] 1 1 True
[239  56 145] 1 1 True
[239  56 146] 1 1 True
[239  57 144] 0 1 False
[239  57 146] 1 1 True
[239  57 147] 1 1 True
[239  58 112] 0 1 False
[239  58 115] 0 1 False
[239  59 112] 0 1 False
[239  59 113] 1 0 False
[239  60  65] 0 1 False
[239  60 130] 1 1 True
[239  60 132] 0 1 False
[239  60 142] 0 1 False
[239  60 146] 0 1 False
[239  60 148] 1 0 False
[239  61  76] 1 1 True
[239  61 118] 1 0 False
[239  61 130] 0 1 False
[239  61 137] 1 0 False
[239  61 139] 0 1 False
[239  61 142] 1 1 True
[239  61 143] 0 1 False
[239  61 146] 1 0 False
[239  61 147] 1 1 True
[239  61 148] 1 1 True
[239  62  76] 0 1 False
[239  62 137] 1 0 False
[239  62 138] 0 1 False
[239  62 141] 0 1 False
[239  62 142] 1 1 True
[239  62 143] 1 1 True
[239  62

[239 228 139] 0 1 False
[239 228 140] 1 1 True
[239 228 141] 0 1 False
[239 228 189] 0 1 False
[239 228 190] 1 1 True
[239 228 191] 0 1 False
[239 228 192] 1 1 True
[239 228 193] 1 1 True
[239 228 194] 1 1 True
[239 228 195] 1 1 True
[239 228 196] 0 1 False
[239 229 139] 1 1 True
[239 229 140] 1 1 True
[239 229 141] 0 1 False
[239 230 139] 1 1 True
[239 230 140] 1 1 True
[239 231  94] 0 1 False
[239 231 141] 1 0 False
[239 231 193] 1 1 True
[239 232 138] 1 1 True
[239 232 193] 0 1 False
[239 233 144] 1 0 False
[239 236  85] 1 0 False
[239 241 205] 0 1 False
[239 241 206] 1 1 True
[239 242 165] 1 1 True
[239 242 206] 1 1 True
[239 243 204] 1 1 True
[239 244 156] 1 0 False
[239 245  81] 1 0 False
[239 245  82] 1 0 False
[239 249 178] 0 1 False
[239 250 187] 1 0 False
[239 254 185] 0 1 False
[239 256 187] 0 1 False
[239 258 158] 0 1 False
[239 258 209] 0 1 False
[239 260  97] 0 1 False
[239 262  96] 0 1 False
[239 262  97] 1 0 False
[239 263  96] 1 1 True
[239 269 184] 1 1 True
[239 270 1

[240  87 162] 0 1 False
[240  88 147] 1 0 False
[240  88 148] 1 1 True
[240  88 149] 0 1 False
[240  88 150] 1 1 True
[240  88 151] 0 1 False
[240  88 161] 0 1 False
[240  88 162] 1 1 True
[240  89 127] 0 1 False
[240  89 161] 1 1 True
[240  90 127] 0 1 False
[240  91  67] 0 1 False
[240  91 119] 1 0 False
[240  92  67] 1 1 True
[240  94 158] 0 1 False
[240  94 159] 1 0 False
[240  94 160] 1 1 True
[240  95 161] 1 1 True
[240  96 103] 1 0 False
[240  96 160] 1 1 True
[240  96 161] 1 1 True
[240  96 162] 1 0 False
[240  97 105] 1 1 True
[240  99 138] 1 0 False
[240  99 164] 0 1 False
[240 104 128] 1 0 False
[240 106 119] 0 1 False
[240 106 120] 0 1 False
[240 106 139] 1 1 True
[240 106 140] 0 1 False
[240 107 164] 0 1 False
[240 108 153] 0 1 False
[240 109  74] 0 1 False
[240 110 170] 1 0 False
[240 112  92] 1 0 False
[240 112 171] 1 0 False
[240 113 139] 1 0 False
[240 116 152] 1 1 True
[240 116 153] 1 1 True
[240 117  68] 0 1 False
[240 117 142] 0 1 False
[240 117 143] 1 0 False
[240 

[241  67 144] 1 1 True
[241  67 145] 1 1 True
[241  67 146] 1 1 True
[241  67 147] 1 1 True
[241  67 149] 1 1 True
[241  67 150] 0 1 False
[241  67 152] 1 1 True
[241  68  10] 0 1 False
[241  68 140] 0 1 False
[241  68 141] 1 1 True
[241  68 142] 1 1 True
[241  68 144] 1 1 True
[241  68 145] 1 1 True
[241  68 146] 1 1 True
[241  68 147] 1 1 True
[241  68 148] 1 1 True
[241  68 149] 1 1 True
[241  68 150] 1 1 True
[241  68 151] 0 1 False
[241  68 152] 1 0 False
[241  69 140] 1 1 True
[241  69 141] 1 1 True
[241  69 142] 0 1 False
[241  69 143] 1 1 True
[241  69 144] 1 1 True
[241  69 147] 1 1 True
[241  69 148] 1 1 True
[241  69 149] 1 1 True
[241  69 150] 1 1 True
[241  69 151] 1 0 False
[241  70 139] 1 1 True
[241  70 140] 1 1 True
[241  70 141] 0 1 False
[241  70 143] 0 1 False
[241  70 145] 0 1 False
[241  70 147] 1 1 True
[241  70 148] 1 1 True
[241  70 149] 1 1 True
[241  70 150] 1 1 True
[241  70 151] 1 1 True
[241  71 138] 1 1 True
[241  71 140] 0 1 False
[241  71 141] 1 0 False

[242  14  69] 1 1 True
[242  14  70] 1 1 True
[242  14 104] 1 1 True
[242  15  64] 1 1 True
[242  15  65] 0 1 False
[242  15  66] 1 0 False
[242  15  67] 1 1 True
[242  15  68] 1 1 True
[242  15  69] 1 1 True
[242  15  88] 0 1 False
[242  15 105] 1 0 False
[242  15 106] 1 1 True
[242  15 107] 1 1 True
[242  15 117] 1 0 False
[242  16  61] 1 0 False
[242  16  62] 0 1 False
[242  16  63] 0 1 False
[242  16  64] 1 1 True
[242  16  65] 1 1 True
[242  16  66] 1 1 True
[242  16  67] 1 1 True
[242  16  68] 1 1 True
[242  16 107] 0 1 False
[242  16 108] 0 1 False
[242  16 110] 1 0 False
[242  16 117] 1 1 True
[242  17  64] 1 1 True
[242  17  66] 1 1 True
[242  17  67] 0 1 False
[242  17  68] 1 0 False
[242  18 116] 1 0 False
[242  19 114] 1 1 True
[242  19 115] 1 1 True
[242  19 121] 1 0 False
[242  20  39] 1 0 False
[242  20  65] 0 1 False
[242  20  98] 1 1 True
[242  20 115] 0 1 False
[242  21  41] 0 1 False
[242  21  68] 1 0 False
[242  21  97] 1 0 False
[242  21  98] 1 1 True
[242  22  11]

[242 148 116] 1 0 False
[242 148 118] 0 1 False
[242 148 119] 0 1 False
[242 148 151] 1 1 True
[242 149  76] 1 0 False
[242 149 118] 1 0 False
[242 150 113] 0 1 False
[242 152 168] 1 1 True
[242 158 118] 1 0 False
[242 158 125] 0 1 False
[242 159 173] 1 1 True
[242 159 174] 1 1 True
[242 159 175] 0 1 False
[242 160 172] 1 0 False
[242 160 173] 1 1 True
[242 160 174] 1 1 True
[242 160 175] 1 1 True
[242 160 176] 1 0 False
[242 161 173] 1 1 True
[242 161 174] 1 1 True
[242 161 175] 0 1 False
[242 162 172] 0 1 False
[242 162 173] 1 1 True
[242 162 174] 1 1 True
[242 163 174] 0 1 False
[242 163 175] 1 0 False
[242 164 173] 1 1 True
[242 164 174] 1 1 True
[242 164 175] 1 0 False
[242 165 174] 1 1 True
[242 166 173] 1 1 True
[242 167 172] 1 1 True
[242 169 121] 1 0 False
[242 173 145] 1 0 False
[242 177  94] 0 1 False
[242 177 120] 0 1 False
[242 179 170] 0 1 False
[242 180 169] 0 1 False
[242 180 170] 1 1 True
[242 180 209] 1 0 False
[242 181 169] 0 1 False
[242 183 161] 1 0 False
[242 184 

[243  77 159] 1 0 False
[243  78  18] 0 1 False
[243  78 152] 1 1 True
[243  78 153] 1 1 True
[243  78 154] 1 1 True
[243  78 155] 1 1 True
[243  78 156] 1 1 True
[243  78 159] 1 1 True
[243  78 160] 1 1 True
[243  79 149] 1 1 True
[243  79 152] 1 1 True
[243  79 153] 1 1 True
[243  79 154] 1 1 True
[243  79 155] 1 0 False
[243  79 157] 0 1 False
[243  79 158] 0 1 False
[243  80 103] 1 1 True
[243  80 152] 1 1 True
[243  80 153] 1 1 True
[243  80 154] 1 1 True
[243  80 155] 0 1 False
[243  80 156] 1 1 True
[243  80 157] 0 1 False
[243  80 159] 1 0 False
[243  80 160] 1 1 True
[243  81  75] 0 1 False
[243  81 103] 0 1 False
[243  81 152] 0 1 False
[243  81 153] 1 1 True
[243  81 154] 1 1 True
[243  81 155] 1 1 True
[243  81 156] 1 1 True
[243  81 157] 0 1 False
[243  81 158] 0 1 False
[243  81 160] 0 1 False
[243  82 152] 0 1 False
[243  82 153] 1 1 True
[243  82 154] 1 1 True
[243  82 155] 1 0 False
[243  82 156] 1 0 False
[243  82 158] 1 1 True
[243  82 159] 1 1 True
[243  82 160] 0 1

[244  61 135] 0 1 False
[244  61 137] 1 1 True
[244  61 142] 1 1 True
[244  61 143] 0 1 False
[244  61 146] 1 1 True
[244  61 147] 1 1 True
[244  61 148] 1 1 True
[244  62 137] 1 0 False
[244  62 140] 0 1 False
[244  62 141] 0 1 False
[244  62 142] 1 1 True
[244  62 143] 1 1 True
[244  62 144] 0 1 False
[244  62 145] 1 1 True
[244  62 147] 1 1 True
[244  62 148] 1 1 True
[244  62 149] 1 1 True
[244  63  55] 0 1 False
[244  63 114] 0 1 False
[244  63 136] 1 1 True
[244  63 137] 1 0 False
[244  63 139] 1 0 False
[244  63 140] 1 1 True
[244  63 141] 1 1 True
[244  63 142] 1 1 True
[244  63 143] 1 1 True
[244  63 144] 1 1 True
[244  63 147] 1 0 False
[244  63 148] 1 1 True
[244  63 149] 1 1 True
[244  63 150] 1 1 True
[244  64 134] 1 0 False
[244  64 136] 1 1 True
[244  64 137] 1 1 True
[244  64 138] 1 1 True
[244  64 139] 1 1 True
[244  64 140] 1 1 True
[244  64 141] 1 1 True
[244  64 142] 1 1 True
[244  64 143] 1 1 True
[244  64 144] 1 1 True
[244  64 145] 1 1 True
[244  64 146] 0 1 Fals

[244 252 187] 0 1 False
[244 256 187] 0 1 False
[244 257 209] 0 1 False
[244 258 157] 0 1 False
[244 258 158] 0 1 False
[244 258 209] 0 1 False
[244 259 111] 0 1 False
[244 262  97] 1 1 True
[244 263  96] 1 1 True
[244 269 184] 1 0 False
[244 270 184] 1 1 True
[244 273  88] 0 1 False
[244 287 143] 0 1 False
[244 287 144] 0 1 False
[244 290 127] 1 0 False
[244 291 163] 0 1 False
[244 292 168] 0 1 False
[245   1  63] 0 1 False
[245   4  45] 0 1 False
[245   5  45] 1 0 False
[245   6  48] 1 0 False
[245   9 101] 1 1 True
[245  10 101] 0 1 False
[245  10 102] 1 1 True
[245  10 103] 1 0 False
[245  11  69] 1 1 True
[245  11 102] 1 0 False
[245  11 103] 1 0 False
[245  12  67] 0 1 False
[245  13  68] 1 0 False
[245  14  64] 0 1 False
[245  14  65] 1 1 True
[245  14  66] 0 1 False
[245  14  68] 1 1 True
[245  14  69] 1 1 True
[245  14  70] 1 1 True
[245  14 104] 1 1 True
[245  15  63] 0 1 False
[245  15  64] 1 1 True
[245  15  65] 0 1 False
[245  15  66] 1 1 True
[245  15  67] 1 1 True
[245  

[245 116 152] 1 1 True
[245 116 153] 1 1 True
[245 117 143] 1 1 True
[245 117 152] 1 1 True
[245 117 153] 0 1 False
[245 117 154] 1 1 True
[245 118 151] 1 1 True
[245 118 152] 1 1 True
[245 118 153] 1 0 False
[245 119 151] 0 1 False
[245 119 152] 1 0 False
[245 124 175] 1 0 False
[245 125 175] 0 1 False
[245 130 148] 1 0 False
[245 130 153] 1 0 False
[245 131  67] 0 1 False
[245 132 153] 1 1 True
[245 133 153] 1 0 False
[245 141 160] 1 1 True
[245 145 115] 1 0 False
[245 145 116] 0 1 False
[245 145 117] 1 1 True
[245 146  98] 1 0 False
[245 146 116] 0 1 False
[245 146 117] 1 1 True
[245 147 109] 0 1 False
[245 147 113] 1 1 True
[245 147 114] 0 1 False
[245 147 115] 1 1 True
[245 147 116] 0 1 False
[245 147 117] 1 0 False
[245 147 118] 1 1 True
[245 147 165] 1 0 False
[245 148  77] 0 1 False
[245 148  78] 1 1 True
[245 148 114] 1 1 True
[245 148 115] 1 1 True
[245 148 116] 1 0 False
[245 148 118] 0 1 False
[245 148 151] 1 1 True
[245 149  76] 1 0 False
[245 149  77] 0 1 False
[245 149  

[246  72  18] 0 1 False
[246  72 138] 0 1 False
[246  72 139] 1 1 True
[246  72 146] 0 1 False
[246  72 147] 1 0 False
[246  72 149] 1 1 True
[246  72 150] 1 1 True
[246  72 151] 1 1 True
[246  73 136] 0 1 False
[246  73 138] 1 1 True
[246  73 139] 1 1 True
[246  73 140] 1 1 True
[246  73 141] 1 1 True
[246  73 144] 0 1 False
[246  73 149] 1 0 False
[246  73 150] 1 1 True
[246  73 153] 1 1 True
[246  73 154] 1 1 True
[246  74 137] 1 1 True
[246  74 138] 0 1 False
[246  74 140] 0 1 False
[246  74 141] 1 1 True
[246  74 149] 1 0 False
[246  74 150] 1 1 True
[246  74 151] 0 1 False
[246  74 152] 1 1 True
[246  74 153] 1 1 True
[246  75 152] 1 1 True
[246  75 153] 1 1 True
[246  76  29] 1 1 True
[246  76 151] 0 1 False
[246  76 152] 1 1 True
[246  76 153] 1 1 True
[246  76 158] 0 1 False
[246  77 151] 1 1 True
[246  77 152] 1 1 True
[246  77 153] 1 1 True
[246  77 154] 1 1 True
[246  77 155] 1 0 False
[246  77 158] 0 1 False
[246  77 159] 1 1 True
[246  78 152] 1 1 True
[246  78 153] 1 1 T

[247  49 143] 0 1 False
[247  50 102] 0 1 False
[247  51 144] 1 1 True
[247  53  38] 0 1 False
[247  53  79] 0 1 False
[247  53  88] 1 0 False
[247  54 145] 0 1 False
[247  55 105] 1 0 False
[247  55 143] 1 0 False
[247  55 144] 1 1 True
[247  55 145] 1 1 True
[247  55 146] 1 1 True
[247  56  96] 1 1 True
[247  56 144] 1 1 True
[247  56 145] 1 1 True
[247  56 146] 1 1 True
[247  57 133] 0 1 False
[247  57 146] 1 1 True
[247  57 147] 1 1 True
[247  58 103] 0 1 False
[247  59  79] 0 1 False
[247  59 113] 1 0 False
[247  60 130] 1 0 False
[247  60 142] 0 1 False
[247  60 146] 0 1 False
[247  60 147] 0 1 False
[247  60 148] 1 0 False
[247  61  26] 0 1 False
[247  61  76] 1 1 True
[247  61  77] 0 1 False
[247  61 117] 0 1 False
[247  61 118] 1 0 False
[247  61 137] 1 1 True
[247  61 142] 1 1 True
[247  61 146] 1 1 True
[247  61 147] 1 1 True
[247  61 148] 1 1 True
[247  62 137] 1 0 False
[247  62 138] 0 1 False
[247  62 140] 0 1 False
[247  62 142] 1 1 True
[247  62 143] 1 1 True
[247  62 1

[247 225 204] 1 1 True
[247 226 116] 0 1 False
[247 226 157] 1 1 True
[247 226 203] 1 0 False
[247 226 204] 1 1 True
[247 226 205] 1 0 False
[247 227 137] 0 1 False
[247 227 146] 0 1 False
[247 227 192] 0 1 False
[247 227 193] 0 1 False
[247 227 194] 1 1 True
[247 227 195] 1 1 True
[247 227 197] 0 1 False
[247 228 139] 0 1 False
[247 228 140] 1 1 True
[247 228 189] 0 1 False
[247 228 190] 1 0 False
[247 228 192] 1 1 True
[247 228 193] 1 1 True
[247 228 194] 1 1 True
[247 228 195] 1 1 True
[247 228 196] 0 1 False
[247 229 139] 1 0 False
[247 229 140] 1 1 True
[247 230 139] 1 0 False
[247 230 140] 1 1 True
[247 231 141] 1 0 False
[247 231 193] 1 0 False
[247 232 138] 1 1 True
[247 233 144] 1 0 False
[247 236  85] 1 1 True
[247 240 207] 0 1 False
[247 241 206] 1 1 True
[247 242 165] 1 0 False
[247 242 206] 1 0 False
[247 243 204] 1 1 True
[247 243 206] 0 1 False
[247 244 156] 1 0 False
[247 245  81] 1 1 True
[247 245  82] 1 1 True
[247 245 149] 0 1 False
[247 245 150] 0 1 False
[247 246 1

[248  86 156] 1 1 True
[248  86 157] 0 1 False
[248  86 159] 1 0 False
[248  86 160] 1 0 False
[248  86 161] 1 1 True
[248  87 148] 1 1 True
[248  87 149] 1 1 True
[248  87 150] 1 0 False
[248  87 159] 1 0 False
[248  87 160] 1 1 True
[248  87 161] 1 0 False
[248  88 147] 1 1 True
[248  88 148] 1 0 False
[248  88 150] 1 1 True
[248  88 151] 0 1 False
[248  88 161] 0 1 False
[248  88 162] 1 1 True
[248  89 146] 0 1 False
[248  89 161] 1 0 False
[248  89 162] 0 1 False
[248  90 127] 0 1 False
[248  91 119] 1 0 False
[248  92  67] 1 1 True
[248  94 158] 0 1 False
[248  94 159] 1 1 True
[248  94 160] 1 1 True
[248  95 161] 1 1 True
[248  96 103] 1 1 True
[248  96 160] 1 0 False
[248  96 161] 1 1 True
[248  96 162] 1 0 False
[248  97 105] 1 1 True
[248  99 138] 1 1 True
[248 104 128] 1 1 True
[248 105 120] 0 1 False
[248 105 163] 0 1 False
[248 106 121] 0 1 False
[248 106 139] 1 1 True
[248 109  74] 0 1 False
[248 110 170] 1 0 False
[248 112  92] 1 1 True
[248 112 171] 1 0 False
[248 113 13

[249  66 150] 1 1 True
[249  66 151] 1 1 True
[249  66 152] 1 0 False
[249  67  66] 0 1 False
[249  67  67] 0 1 False
[249  67 138] 1 0 False
[249  67 139] 0 1 False
[249  67 140] 1 1 True
[249  67 141] 1 1 True
[249  67 142] 1 1 True
[249  67 143] 1 1 True
[249  67 144] 1 1 True
[249  67 145] 1 1 True
[249  67 146] 1 1 True
[249  67 147] 1 1 True
[249  67 149] 1 1 True
[249  67 150] 0 1 False
[249  67 152] 1 1 True
[249  68 121] 0 1 False
[249  68 140] 0 1 False
[249  68 141] 1 1 True
[249  68 142] 1 0 False
[249  68 143] 0 1 False
[249  68 144] 1 1 True
[249  68 145] 1 1 True
[249  68 146] 1 1 True
[249  68 147] 1 1 True
[249  68 148] 1 1 True
[249  68 149] 1 1 True
[249  68 150] 1 1 True
[249  68 151] 0 1 False
[249  68 152] 1 1 True
[249  69 121] 0 1 False
[249  69 140] 1 1 True
[249  69 141] 1 0 False
[249  69 142] 0 1 False
[249  69 143] 1 1 True
[249  69 144] 1 1 True
[249  69 145] 0 1 False
[249  69 147] 1 1 True
[249  69 148] 1 1 True
[249  69 149] 1 1 True
[249  69 150] 1 1 T

[250  27 127] 1 1 True
[250  30 112] 0 1 False
[250  31 128] 1 1 True
[250  31 129] 0 1 False
[250  32  59] 0 1 False
[250  32  61] 1 0 False
[250  32  79] 1 0 False
[250  32 128] 0 1 False
[250  32 129] 1 1 True
[250  32 130] 1 1 True
[250  33  71] 0 1 False
[250  33 128] 0 1 False
[250  33 129] 1 1 True
[250  33 130] 1 1 True
[250  34 128] 0 1 False
[250  34 129] 0 1 False
[250  34 130] 1 1 True
[250  34 131] 1 1 True
[250  34 132] 0 1 False
[250  35  60] 0 1 False
[250  35 104] 0 1 False
[250  35 127] 1 0 False
[250  35 128] 1 1 True
[250  35 130] 1 1 True
[250  35 131] 1 1 True
[250  35 132] 0 1 False
[250  36 104] 1 0 False
[250  36 105] 1 1 True
[250  36 128] 0 1 False
[250  36 132] 1 0 False
[250  36 135] 0 1 False
[250  36 136] 0 1 False
[250  37 130] 1 0 False
[250  37 131] 1 0 False
[250  37 132] 1 1 True
[250  37 134] 1 1 True
[250  37 135] 1 1 True
[250  37 136] 0 1 False
[250  38  59] 1 1 True
[250  38 133] 0 1 False
[250  38 134] 0 1 False
[250  39  59] 1 0 False
[250  40

[250 197 126] 1 0 False
[250 198 126] 1 1 True
[250 199 126] 0 1 False
[250 200 140] 1 1 True
[250 201 105] 0 1 False
[250 205 203] 1 1 True
[250 206 103] 0 1 False
[250 207 172] 0 1 False
[250 208 172] 1 0 False
[250 209 172] 1 1 True
[250 209 174] 0 1 False
[250 210  72] 0 1 False
[250 211  78] 1 0 False
[250 213  67] 1 1 True
[250 214 105] 0 1 False
[250 214 131] 1 0 False
[250 221  97] 0 1 False
[250 222 204] 1 1 True
[250 224  89] 1 0 False
[250 224  90] 1 1 True
[250 224 204] 1 1 True
[250 224 205] 1 1 True
[250 225 203] 1 1 True
[250 225 204] 1 1 True
[250 225 205] 0 1 False
[250 226 143] 0 1 False
[250 226 157] 1 1 True
[250 226 203] 1 0 False
[250 226 204] 1 0 False
[250 226 205] 1 0 False
[250 227 137] 0 1 False
[250 227 193] 0 1 False
[250 227 194] 1 1 True
[250 227 195] 1 1 True
[250 227 196] 0 1 False
[250 227 197] 0 1 False
[250 227 198] 0 1 False
[250 228 139] 0 1 False
[250 228 140] 1 1 True
[250 228 190] 1 0 False
[250 228 192] 1 1 True
[250 228 193] 1 1 True
[250 228 

[251  80 156] 1 1 True
[251  80 157] 0 1 False
[251  80 159] 1 0 False
[251  80 160] 1 1 True
[251  81  60] 0 1 False
[251  81 152] 0 1 False
[251  81 153] 1 1 True
[251  81 154] 1 1 True
[251  81 155] 1 1 True
[251  81 156] 1 1 True
[251  81 157] 0 1 False
[251  81 160] 0 1 False
[251  82 153] 1 0 False
[251  82 154] 1 1 True
[251  82 155] 1 1 True
[251  82 156] 1 0 False
[251  82 158] 1 1 True
[251  82 159] 1 1 True
[251  82 160] 0 1 False
[251  82 161] 1 1 True
[251  83 151] 0 1 False
[251  83 153] 1 0 False
[251  83 155] 1 1 True
[251  83 160] 0 1 False
[251  83 161] 1 1 True
[251  84 152] 1 1 True
[251  84 153] 1 1 True
[251  84 154] 1 1 True
[251  84 155] 1 1 True
[251  84 156] 1 0 False
[251  84 160] 1 0 False
[251  84 161] 1 1 True
[251  85  50] 0 1 False
[251  85  90] 0 1 False
[251  85 150] 1 1 True
[251  85 152] 1 0 False
[251  85 153] 1 1 True
[251  85 154] 1 1 True
[251  85 155] 1 1 True
[251  85 156] 1 0 False
[251  85 161] 1 1 True
[251  86 149] 1 1 True
[251  86 150] 1 

[252  64 136] 1 1 True
[252  64 137] 1 0 False
[252  64 138] 1 1 True
[252  64 139] 1 1 True
[252  64 140] 1 1 True
[252  64 141] 1 0 False
[252  64 142] 1 1 True
[252  64 143] 1 1 True
[252  64 144] 1 1 True
[252  64 145] 1 1 True
[252  64 146] 0 1 False
[252  64 147] 1 1 True
[252  64 148] 1 1 True
[252  64 149] 1 1 True
[252  64 150] 1 1 True
[252  64 151] 1 1 True
[252  65  15] 0 1 False
[252  65  26] 1 1 True
[252  65 136] 0 1 False
[252  65 137] 1 1 True
[252  65 138] 0 1 False
[252  65 139] 1 1 True
[252  65 140] 1 1 True
[252  65 141] 1 1 True
[252  65 142] 1 0 False
[252  65 143] 0 1 False
[252  65 144] 1 1 True
[252  65 145] 1 1 True
[252  65 146] 1 1 True
[252  65 147] 1 1 True
[252  65 148] 1 1 True
[252  65 149] 1 1 True
[252  65 150] 1 1 True
[252  65 151] 1 1 True
[252  66  67] 1 0 False
[252  66 137] 1 1 True
[252  66 138] 1 1 True
[252  66 139] 1 1 True
[252  66 140] 1 1 True
[252  66 141] 1 1 True
[252  66 142] 1 1 True
[252  66 143] 1 1 True
[252  66 144] 1 1 True
[2

[253  17 117] 0 1 False
[253  18 116] 1 0 False
[253  19 114] 1 1 True
[253  19 115] 1 1 True
[253  19 120] 0 1 False
[253  19 121] 1 1 True
[253  20   4] 0 1 False
[253  20  39] 1 0 False
[253  20  98] 1 0 False
[253  20 120] 0 1 False
[253  21  68] 1 0 False
[253  21  97] 1 1 True
[253  21  98] 1 0 False
[253  21 122] 0 1 False
[253  22  12] 1 1 True
[253  22  13] 1 0 False
[253  23  12] 1 1 True
[253  23  13] 1 1 True
[253  23  20] 1 0 False
[253  23  26] 0 1 False
[253  23  53] 1 1 True
[253  23 122] 1 0 False
[253  24 123] 0 1 False
[253  25 124] 1 0 False
[253  26 124] 1 0 False
[253  26 125] 1 1 True
[253  26 126] 1 0 False
[253  27  66] 1 0 False
[253  27 126] 1 0 False
[253  27 127] 1 0 False
[253  29 103] 0 1 False
[253  30  13] 0 1 False
[253  30 112] 0 1 False
[253  31  45] 0 1 False
[253  31  85] 0 1 False
[253  31 128] 1 0 False
[253  31 129] 0 1 False
[253  32  61] 1 0 False
[253  32  79] 1 1 True
[253  32 127] 0 1 False
[253  32 129] 1 1 True
[253  32 130] 1 1 True
[253

[253 164 173] 1 0 False
[253 164 174] 1 1 True
[253 164 175] 1 1 True
[253 165 174] 1 1 True
[253 165 175] 0 1 False
[253 166 173] 1 1 True
[253 166 174] 0 1 False
[253 167 172] 1 0 False
[253 169 121] 1 0 False
[253 172 146] 0 1 False
[253 172 147] 0 1 False
[253 173 145] 1 0 False
[253 173 146] 0 1 False
[253 173 148] 0 1 False
[253 176 155] 0 1 False
[253 177  94] 0 1 False
[253 177  95] 0 1 False
[253 180 169] 0 1 False
[253 180 170] 1 1 True
[253 180 209] 1 0 False
[253 183 161] 1 0 False
[253 184 172] 0 1 False
[253 185 117] 1 1 True
[253 194  78] 0 1 False
[253 196 125] 1 0 False
[253 196 126] 0 1 False
[253 196 127] 0 1 False
[253 197 126] 1 0 False
[253 198 126] 1 1 True
[253 199 141] 0 1 False
[253 200 140] 1 0 False
[253 200 141] 0 1 False
[253 200 180] 0 1 False
[253 201 105] 0 1 False
[253 201 106] 0 1 False
[253 201 143] 0 1 False
[253 205 203] 1 0 False
[253 208 172] 1 0 False
[253 209 172] 1 1 True
[253 209 174] 0 1 False
[253 211  78] 1 0 False
[253 213  67] 1 0 False


[254  74 152] 1 1 True
[254  74 153] 1 1 True
[254  75 140] 0 1 False
[254  75 141] 0 1 False
[254  75 152] 1 1 True
[254  75 153] 1 1 True
[254  76  28] 0 1 False
[254  76  29] 1 1 True
[254  76 143] 0 1 False
[254  76 151] 0 1 False
[254  76 152] 1 1 True
[254  76 153] 1 1 True
[254  77 151] 1 1 True
[254  77 152] 1 1 True
[254  77 153] 1 1 True
[254  77 154] 1 1 True
[254  77 155] 1 1 True
[254  77 158] 0 1 False
[254  77 159] 1 0 False
[254  78 152] 1 1 True
[254  78 153] 1 1 True
[254  78 154] 1 1 True
[254  78 155] 1 1 True
[254  78 156] 1 0 False
[254  78 159] 1 1 True
[254  78 160] 1 0 False
[254  79 149] 1 1 True
[254  79 152] 1 1 True
[254  79 153] 1 1 True
[254  79 154] 1 1 True
[254  79 155] 1 1 True
[254  80 103] 1 0 False
[254  80 152] 1 1 True
[254  80 153] 1 1 True
[254  80 154] 1 1 True
[254  80 156] 1 1 True
[254  80 159] 1 0 False
[254  80 160] 1 1 True
[254  81 152] 0 1 False
[254  81 153] 1 1 True
[254  81 154] 1 1 True
[254  81 155] 1 0 False
[254  81 156] 1 1 Tru

[255  61 142] 1 1 True
[255  61 146] 1 0 False
[255  61 147] 1 1 True
[255  61 148] 1 1 True
[255  62 120] 0 1 False
[255  62 137] 1 0 False
[255  62 138] 0 1 False
[255  62 139] 0 1 False
[255  62 140] 0 1 False
[255  62 142] 1 1 True
[255  62 143] 1 1 True
[255  62 144] 0 1 False
[255  62 145] 1 1 True
[255  62 147] 1 1 True
[255  62 148] 1 1 True
[255  62 149] 1 0 False
[255  63 114] 0 1 False
[255  63 135] 0 1 False
[255  63 136] 1 1 True
[255  63 137] 1 0 False
[255  63 138] 0 1 False
[255  63 139] 1 1 True
[255  63 140] 1 1 True
[255  63 141] 1 1 True
[255  63 142] 1 1 True
[255  63 143] 1 1 True
[255  63 144] 1 1 True
[255  63 147] 1 1 True
[255  63 148] 1 1 True
[255  63 149] 1 1 True
[255  63 150] 1 1 True
[255  64  55] 0 1 False
[255  64 134] 1 0 False
[255  64 136] 1 1 True
[255  64 137] 1 1 True
[255  64 138] 1 1 True
[255  64 139] 1 1 True
[255  64 140] 1 1 True
[255  64 141] 1 1 True
[255  64 142] 1 1 True
[255  64 143] 1 1 True
[255  64 144] 1 1 True
[255  64 145] 1 1 Tr

[256  15  66] 1 1 True
[256  15  67] 1 1 True
[256  15  68] 1 1 True
[256  15  69] 1 1 True
[256  15 105] 1 1 True
[256  15 106] 1 0 False
[256  15 107] 1 0 False
[256  15 117] 1 0 False
[256  16  61] 1 1 True
[256  16  62] 0 1 False
[256  16  64] 1 1 True
[256  16  65] 1 1 True
[256  16  66] 1 0 False
[256  16  67] 1 1 True
[256  16  68] 1 1 True
[256  16 107] 0 1 False
[256  16 110] 1 1 True
[256  16 117] 1 0 False
[256  17  64] 1 1 True
[256  17  65] 0 1 False
[256  17  66] 1 0 False
[256  17  68] 1 1 True
[256  17 108] 0 1 False
[256  17 112] 0 1 False
[256  17 118] 0 1 False
[256  18  58] 0 1 False
[256  18 111] 0 1 False
[256  18 116] 1 0 False
[256  18 117] 0 1 False
[256  19 114] 1 1 True
[256  19 115] 1 1 True
[256  19 121] 1 1 True
[256  20  39] 1 1 True
[256  20  66] 0 1 False
[256  20  98] 1 1 True
[256  20  99] 0 1 False
[256  20 120] 0 1 False
[256  20 121] 0 1 False
[256  21  11] 0 1 False
[256  21  41] 0 1 False
[256  21  68] 1 0 False
[256  21  97] 1 0 False
[256  21  

[256 150 114] 0 1 False
[256 152 168] 1 1 True
[256 158 118] 1 0 False
[256 158 125] 0 1 False
[256 159 173] 1 1 True
[256 159 174] 1 1 True
[256 160 172] 1 1 True
[256 160 173] 1 1 True
[256 160 174] 1 1 True
[256 160 175] 1 1 True
[256 160 176] 1 1 True
[256 161 172] 0 1 False
[256 161 173] 1 1 True
[256 161 174] 1 1 True
[256 162 173] 1 1 True
[256 162 174] 1 1 True
[256 163 173] 0 1 False
[256 163 175] 1 1 True
[256 164 173] 1 1 True
[256 164 174] 1 1 True
[256 164 175] 1 1 True
[256 165 174] 1 1 True
[256 166 173] 1 1 True
[256 167 172] 1 1 True
[256 169 121] 1 0 False
[256 173 145] 1 0 False
[256 173 146] 0 1 False
[256 173 175] 0 1 False
[256 177  95] 0 1 False
[256 177 120] 0 1 False
[256 179 170] 0 1 False
[256 180 169] 0 1 False
[256 180 170] 1 1 True
[256 180 209] 1 0 False
[256 181 169] 0 1 False
[256 181 170] 0 1 False
[256 183 161] 1 0 False
[256 184 172] 0 1 False
[256 185 117] 1 1 True
[256 194  78] 0 1 False
[256 196 125] 1 0 False
[256 197 126] 1 0 False
[256 198 126]

[257  69 149] 1 1 True
[257  69 150] 1 1 True
[257  69 151] 1 0 False
[257  70 139] 1 0 False
[257  70 140] 1 1 True
[257  70 141] 0 1 False
[257  70 142] 0 1 False
[257  70 143] 0 1 False
[257  70 145] 0 1 False
[257  70 147] 1 1 True
[257  70 148] 1 1 True
[257  70 149] 1 1 True
[257  70 150] 1 1 True
[257  70 151] 1 0 False
[257  71 138] 1 0 False
[257  71 139] 0 1 False
[257  71 140] 0 1 False
[257  71 141] 1 1 True
[257  71 142] 0 1 False
[257  71 146] 1 1 True
[257  71 148] 1 1 True
[257  71 149] 1 1 True
[257  71 150] 1 1 True
[257  72 139] 1 1 True
[257  72 147] 1 1 True
[257  72 149] 1 1 True
[257  72 150] 1 1 True
[257  72 151] 1 1 True
[257  73 137] 0 1 False
[257  73 138] 1 1 True
[257  73 139] 1 1 True
[257  73 140] 1 1 True
[257  73 141] 1 0 False
[257  73 149] 1 0 False
[257  73 150] 1 1 True
[257  73 153] 1 1 True
[257  73 154] 1 1 True
[257  74 137] 1 0 False
[257  74 138] 0 1 False
[257  74 140] 0 1 False
[257  74 141] 1 1 True
[257  74 142] 0 1 False
[257  74 149] 1 

[258  45  80] 1 0 False
[258  46  13] 0 1 False
[258  46  14] 1 1 True
[258  46 124] 0 1 False
[258  46 141] 1 0 False
[258  47 132] 1 0 False
[258  47 142] 0 1 False
[258  48 143] 0 1 False
[258  48 144] 1 0 False
[258  49 143] 0 1 False
[258  50 102] 0 1 False
[258  51 144] 1 0 False
[258  53  88] 1 0 False
[258  53 131] 0 1 False
[258  55 105] 1 1 True
[258  55 143] 1 0 False
[258  55 144] 1 0 False
[258  55 145] 1 1 True
[258  55 146] 1 1 True
[258  56  96] 1 1 True
[258  56 143] 0 1 False
[258  56 144] 1 1 True
[258  56 145] 1 0 False
[258  56 146] 1 1 True
[258  56 147] 0 1 False
[258  57 146] 1 1 True
[258  57 147] 1 1 True
[258  58 112] 0 1 False
[258  59 112] 0 1 False
[258  59 113] 1 0 False
[258  60 130] 1 0 False
[258  60 147] 0 1 False
[258  60 148] 1 0 False
[258  61  76] 1 0 False
[258  61  77] 0 1 False
[258  61 118] 1 0 False
[258  61 137] 1 0 False
[258  61 139] 0 1 False
[258  61 142] 1 1 True
[258  61 146] 1 1 True
[258  61 147] 1 1 True
[258  61 148] 1 1 True
[258 

[258 224  89] 1 0 False
[258 224  90] 1 1 True
[258 224 204] 1 1 True
[258 224 205] 1 0 False
[258 225 193] 0 1 False
[258 225 203] 1 1 True
[258 225 204] 1 1 True
[258 226 143] 0 1 False
[258 226 157] 1 1 True
[258 226 194] 0 1 False
[258 226 203] 1 1 True
[258 226 204] 1 0 False
[258 226 205] 1 0 False
[258 227 137] 0 1 False
[258 227 190] 0 1 False
[258 227 191] 0 1 False
[258 227 193] 0 1 False
[258 227 194] 1 1 True
[258 227 195] 1 0 False
[258 227 196] 0 1 False
[258 227 197] 0 1 False
[258 227 202] 0 1 False
[258 228 139] 0 1 False
[258 228 140] 1 1 True
[258 228 190] 1 0 False
[258 228 191] 0 1 False
[258 228 192] 1 1 True
[258 228 193] 1 1 True
[258 228 194] 1 1 True
[258 228 195] 1 1 True
[258 229 139] 1 1 True
[258 229 140] 1 1 True
[258 230 139] 1 1 True
[258 230 140] 1 1 True
[258 231  94] 0 1 False
[258 231 141] 1 0 False
[258 231 193] 1 1 True
[258 232 138] 1 0 False
[258 233 100] 0 1 False
[258 233 144] 1 0 False
[258 236  85] 1 0 False
[258 238 200] 0 1 False
[258 241 

[259  84 153] 1 0 False
[259  84 154] 1 1 True
[259  84 155] 1 1 True
[259  84 156] 1 0 False
[259  84 157] 0 1 False
[259  84 160] 1 0 False
[259  84 161] 1 1 True
[259  85 150] 1 1 True
[259  85 152] 1 0 False
[259  85 153] 1 0 False
[259  85 154] 1 1 True
[259  85 155] 1 1 True
[259  85 156] 1 0 False
[259  85 161] 1 1 True
[259  86 148] 0 1 False
[259  86 149] 1 1 True
[259  86 150] 1 1 True
[259  86 151] 1 1 True
[259  86 154] 1 1 True
[259  86 155] 0 1 False
[259  86 156] 1 0 False
[259  86 157] 0 1 False
[259  86 159] 1 1 True
[259  86 160] 1 1 True
[259  86 161] 1 1 True
[259  87 148] 1 1 True
[259  87 149] 1 1 True
[259  87 150] 1 0 False
[259  87 159] 1 1 True
[259  87 160] 1 1 True
[259  87 161] 1 1 True
[259  87 162] 0 1 False
[259  88 147] 1 1 True
[259  88 148] 1 1 True
[259  88 149] 0 1 False
[259  88 150] 1 1 True
[259  88 151] 0 1 False
[259  88 162] 1 1 True
[259  89 127] 0 1 False
[259  89 161] 1 0 False
[259  89 162] 0 1 False
[259  90 146] 0 1 False
[259  91  67] 0

[260  65 143] 0 1 False
[260  65 144] 1 1 True
[260  65 145] 1 1 True
[260  65 146] 1 1 True
[260  65 147] 1 1 True
[260  65 148] 1 1 True
[260  65 149] 1 1 True
[260  65 150] 1 1 True
[260  65 151] 1 1 True
[260  66  67] 1 0 False
[260  66 137] 1 1 True
[260  66 138] 1 1 True
[260  66 139] 1 1 True
[260  66 140] 1 1 True
[260  66 141] 1 1 True
[260  66 142] 1 1 True
[260  66 143] 1 1 True
[260  66 144] 1 1 True
[260  66 145] 1 0 False
[260  66 146] 1 1 True
[260  66 147] 1 1 True
[260  66 148] 1 1 True
[260  66 149] 1 1 True
[260  66 150] 1 1 True
[260  66 151] 1 1 True
[260  66 152] 1 1 True
[260  67  66] 0 1 False
[260  67 136] 0 1 False
[260  67 138] 1 0 False
[260  67 139] 0 1 False
[260  67 140] 1 1 True
[260  67 141] 1 1 True
[260  67 142] 1 1 True
[260  67 143] 1 1 True
[260  67 144] 1 1 True
[260  67 145] 1 1 True
[260  67 146] 1 1 True
[260  67 147] 1 0 False
[260  67 149] 1 1 True
[260  67 152] 1 1 True
[260  68  99] 0 1 False
[260  68 121] 0 1 False
[260  68 136] 0 1 False


[260 286 144] 0 1 False
[260 287 125] 0 1 False
[260 287 126] 0 1 False
[260 287 143] 0 1 False
[260 290 127] 1 0 False
[260 306 125] 0 1 False
Taxa de acerto:  0.4713565123401189


## Pipeline com granularidade 1000
Celulas com tamanho de 0.001°

In [14]:
# df = pd.read_excel('dataframe_8.xlsx')

In [15]:
'''
X, y = split_cube(build_cube(df.col.values, df.row.values, df.week_number.values))
y = convert_y_to_binary(y)
'''

'\nX, y = split_cube(build_cube(df.col.values, df.row.values, df.week_number.values))\ny = convert_y_to_binary(y)\n'

In [16]:
'''
from sklearn.model_selection import train_test_split

# Separando Treino e Teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

y_pred = predict_with_rf(X_train, X_test, y_train, y_test)
acerto = compara_acertos(X_test, y_test, y_pred)
print("Taxa de acerto: ", acerto)
'''

'\nfrom sklearn.model_selection import train_test_split\n\n# Separando Treino e Teste\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)\n\ny_pred = predict_with_rf(X_train, X_test, y_train, y_test)\nacerto = compara_acertos(X_test, y_test, y_pred)\nprint("Taxa de acerto: ", acerto)\n'

In [11]:
import tensorflow as tf

ModuleNotFoundError: No module named 'tensorflow'

In [ ]:
l0 = tf.keras.layers.Dense(units=1, input_shape=[3]) 
model = tf.keras.Sequential([l0])
model.compile(optimizer=tf.keras.optimizers.SGD())
history = model.fit(X_train, y_train, epochs=10, verbose=False)

In [15]:
result = model.predict(X_test)

In [16]:
result

array([[-2.6353285],
       [-2.6438603],
       [-2.6523921],
       ...,
       [-3.291924 ],
       [-3.3004556],
       [-3.3089874]], dtype=float32)

In [17]:
y_train

array([[0],
       [0],
       [0],
       ...,
       [1],
       [1],
       [0]])